# Generated by Django 2.0.7 on 2018-08-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='planned_departure_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
