# Generated by Django 2.0.7 on 2018-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_timetable_planned_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='shape_dist_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='stop_headsign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
