# Generated by Django 2.0.7 on 2018-08-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_auto_20180807_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='shape_dist_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
