# Generated by Django 2.0.7 on 2018-08-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_shape_shape_dist_traveled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape',
            old_name='shape_dist_traveled',
            new_name='next_shape_dist',
        ),
    ]
