# Generated by Django 2.0.6 on 2018-07-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distance_timetable_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=500)),
                ('arrival_time', models.CharField(max_length=500)),
                ('departure_time', models.CharField(max_length=500)),
                ('prog_number', models.CharField(max_length=500)),
                ('stop_headsign', models.CharField(max_length=500)),
                ('shape_dist_traveled', models.CharField(max_length=500)),
                ('new_stop_id', models.CharField(max_length=500)),
                ('line_ID', models.CharField(max_length=500)),
                ('weekday', models.CharField(max_length=500)),
                ('direction', models.CharField(max_length=500)),
                ('distance', models.CharField(max_length=500)),
                ('previous_stopID', models.CharField(max_length=500)),
            ],
        ),
    ]
