# 8.6 Timetable update
1. Add two columns - hour and shape_dist_traveled
2. change the distance period

In [93]:
import pandas as pd
import numpy as np
import re

In [94]:
distance = pd.read_csv("stop_times.txt", sep=',')
distance.head()

trip_id arrival_time departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O     15:40:00       15:40:00  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O     15:40:47       15:40:47  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O     15:41:26       15:41:26  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O     15:42:30       15:42:30  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O     15:43:09       15:43:09  8240DB000230   

   stop_sequence stop_headsign  pickup_type  drop_off_type  \
0              1    Sandymount            0              0   
1              2    Sandymount            0              0   
2              3    Sandymount            0              0   
3              4    Sandymount            0              0   
4              5    Sandymount            0              0   

   shape_dist_traveled  
0             0.000000  
1           261.136188  
2           484.925289  
3           836.995679  
4          1066.461783

In [95]:
distance.shape

(926205, 9)

In [96]:
trip1=[]
trip2=[]
trip3=[]
trip4=[]
shape=[]
for index, row in distance.iterrows():
    trip_list = row["trip_id"].split('-')
    shape_list = '.'.join(row["trip_id"].split('.')[2:])
    trip1.append(trip_list[0])
    trip2.append(trip_list[1])
    trip3.append(trip_list[2])
    trip4.append(trip_list[3])
    shape.append(shape_list)

In [97]:
distance['trip1']=trip1
distance['trip2']=trip2
distance['trip3']=trip3
distance['trip4']=trip4
distance['shape_id'] =shape

In [98]:
distance['new_stop_id'] = distance.stop_id.str.extract('([1-9][0-9]*\Z)', expand=True)

issue: some unnamed stop' IDs will be all commpressed to 1, should be fixed.

In [99]:
distance.head()

trip_id arrival_time departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O     15:40:00       15:40:00  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O     15:40:47       15:40:47  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O     15:41:26       15:41:26  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O     15:42:30       15:42:30  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O     15:43:09       15:43:09  8240DB000230   

   stop_sequence stop_headsign  pickup_type  drop_off_type  \
0              1    Sandymount            0              0   
1              2    Sandymount            0              0   
2              3    Sandymount            0              0   
3              4    Sandymount            0              0   
4              5    Sandymount            0              0   

   shape_dist_traveled          trip1 trip2 trip3  trip4        shape_id  \
0             0.000000  3643.y102m.60     1   d12  1.1.O  60-1-d12-1.1.O   
1           261.136188  3643.y102m.60     1   d12  1.1.O  60-1-d12-1.1.O   
2           484.925289  3643.y102m.60     1   d12  1.1.O  60-1-d12-1.1.O   
3           836.995679  3643.y102m.60     1   d12  1.1.O  60-1-d12-1.1.O   
4          1066.461783  3643.y102m.60     1   d12  1.1.O  60-1-d12-1.1.O   

  new_stop_id  
0         226  
1         228  
2         229  
3         227  
4         230

In [100]:
len(distance.shape_id.unique())

509

In [101]:
distance[distance['new_stop_id'] == '1'].trip2.unique()

array(['18', '47', '68', '68A', '68X', '69', '69X', '7D'], dtype=object)

In [102]:
# pattern = '-([0-9]*[A-Za-z])-'
# distance['new_lines_id'] = distance.trip_id.str.extract(pattern, expand=True)

## 1.1 check the stop id

# the issus with extract function
1. the stopid provided by google and dublin bus are not same.
2. The extract function which convent between them results in the mistake with stop_id 1, google map has strange format with serveral stop not usual , these unusual should be careful checked

In [103]:
distance[distance["new_stop_id"]=='1'].stop_id.unique()

array(['gen:57102:5245:0:1', 'gen:57102:3542:0:1', 'gen:57102:3543:0:1',
       'gen:57102:3607:0:1', 'gen:57102:3606:0:1'], dtype=object)

In [104]:
len(distance[distance["new_stop_id"]=='1'])

299

In [105]:
distance[distance["new_stop_id"]=='1']

trip_id arrival_time departure_time  \
313672     324.y102m.60-18-d12-1.48.I     07:58:07       07:58:07   
313734     326.y102m.60-18-d12-1.48.I     06:23:07       06:23:07   
313796     335.y102m.60-18-d12-1.48.I     07:13:07       07:13:07   
313858     337.y102m.60-18-d12-1.48.I     06:43:07       06:43:07   
313920     339.y102m.60-18-d12-1.48.I     06:58:07       06:58:07   
313982     342.y102m.60-18-d12-1.48.I     07:43:07       07:43:07   
314044     379.y102m.60-18-d12-1.48.I     07:28:07       07:28:07   
314106     374.y102m.60-18-d12-1.48.I     21:13:13       21:13:13   
314168     376.y102m.60-18-d12-1.48.I     23:33:13       23:33:13   
314230     409.y102m.60-18-d12-1.48.I     22:33:13       22:33:13   
314292   13645.y102n.60-18-d12-1.48.I     19:23:07       19:23:07   
314354   13651.y102n.60-18-d12-1.48.I     20:13:07       20:13:07   
314416   13619.y102n.60-18-d12-1.48.I     10:42:55       10:42:55   
314478   13625.y102n.60-18-d12-1.48.I     11:17:55       11:17:55   
314540   13629.y102n.60-18-d12-1.48.I     11:52:55       11:52:55   
314602    7928.y102o.60-18-d12-1.48.I     13:24:53       13:24:53   
314664    7949.y102o.60-18-d12-1.48.I     14:24:53       14:24:53   
314726    7954.y102o.60-18-d12-1.48.I     12:14:53       12:14:53   
314788    7956.y102o.60-18-d12-1.48.I     14:54:53       14:54:53   
314850    7958.y102o.60-18-d12-1.48.I     12:34:53       12:34:53   
314912    7960.y102o.60-18-d12-1.48.I     12:49:53       12:49:53   
314974    7962.y102o.60-18-d12-1.48.I     14:04:53       14:04:53   
315036    7964.y102o.60-18-d12-1.48.I     15:26:31       15:26:31   
315098    7966.y102o.60-18-d12-1.48.I     18:01:31       18:01:31   
315160    7968.y102o.60-18-d12-1.48.I     15:56:31       15:56:31   
315222    7970.y102o.60-18-d12-1.48.I     17:26:31       17:26:31   
315284    7972.y102o.60-18-d12-1.48.I     18:36:31       18:36:31   
315346    7985.y102o.60-18-d12-1.48.I     17:01:31       17:01:31   
315408    9372.y102o.60-18-d12-1.48.I     16:26:31       16:26:31   
315470    9374.y102o.60-18-d12-1.48.I     19:06:31       19:06:31   
...                               ...          ...            ...   
780083  16500.y102n.60-69-d12-1.416.I     15:24:25       15:24:25   
780144  12007.y102o.60-69-d12-1.416.I     22:17:11       22:17:11   
780205  12041.y102o.60-69-d12-1.416.I     23:57:11       23:57:11   
780266  12053.y102o.60-69-d12-1.416.I     22:57:11       22:57:11   
780327  16524.y102n.60-69-d12-1.416.I     22:52:12       22:52:12   
780388  12008.y102o.60-69-d12-1.416.I     07:47:05       07:47:05   
780449  12031.y102o.60-69-d12-1.416.I     08:37:05       08:37:05   
780510  12043.y102o.60-69-d12-1.416.I     08:22:05       08:22:05   
780571  12056.y102o.60-69-d12-1.416.I     07:07:05       07:07:05   
781655   6231.y102m.60-69-d12-1.419.I     06:58:27       06:58:27   
781716   6291.y102m.60-69-d12-1.419.I     15:33:57       15:33:57   
781777   6355.y102m.60-69-d12-1.419.I     17:47:41       17:47:41   
781838   6289.y102m.60-69-d12-1.419.I     12:32:18       12:32:18   
781899   6351.y102m.60-69-d12-1.419.I     11:32:18       11:32:18   
781960   6294.y102m.60-69-d12-1.419.I     08:31:19       08:31:19   
782021   6336.y102m.60-69-d12-1.419.I     08:01:19       08:01:19   
782082   6296.y102m.60-69-d12-1.419.I     13:32:49       13:32:49   
782143   6353.y102m.60-69-d12-1.419.I     14:32:49       14:32:49   
782204   6308.y102m.60-69-d12-1.419.I     24:02:35       24:02:35   
782265   6333.y102m.60-69-d12-1.419.I     22:02:35       22:02:35   
782326   6359.y102m.60-69-d12-1.419.I     23:02:35       23:02:35   
782387   6304.y102m.60-69-d12-1.419.I     18:45:59       18:45:59   
782448   6306.y102m.60-69-d12-1.419.I     21:09:32       21:09:32   
782509   6310.y102m.60-69-d12-1.419.I     19:24:32       19:24:32   
782570   6357.y102m.60-69-d12-1.419.I     20:24:32       20:24:32   
782631   6233.y102m.60-69-d12-1.419.I     09:29:00       09:29:00   
782692   6298.y102m.60-69-d1

In [106]:
distance[distance["trip_id"]=='324.y102m.60-18-d12-1.48.I']

trip_id arrival_time departure_time  \
313657  324.y102m.60-18-d12-1.48.I     07:45:00       07:45:00   
313658  324.y102m.60-18-d12-1.48.I     07:46:17       07:46:17   
313659  324.y102m.60-18-d12-1.48.I     07:46:47       07:46:47   
313660  324.y102m.60-18-d12-1.48.I     07:47:29       07:47:29   
313661  324.y102m.60-18-d12-1.48.I     07:49:24       07:49:24   
313662  324.y102m.60-18-d12-1.48.I     07:50:36       07:50:36   
313663  324.y102m.60-18-d12-1.48.I     07:51:09       07:51:09   
313664  324.y102m.60-18-d12-1.48.I     07:52:14       07:52:14   
313665  324.y102m.60-18-d12-1.48.I     07:52:41       07:52:41   
313666  324.y102m.60-18-d12-1.48.I     07:53:22       07:53:22   
313667  324.y102m.60-18-d12-1.48.I     07:54:09       07:54:09   
313668  324.y102m.60-18-d12-1.48.I     07:55:14       07:55:14   
313669  324.y102m.60-18-d12-1.48.I     07:56:18       07:56:18   
313670  324.y102m.60-18-d12-1.48.I     07:56:59       07:56:59   
313671  324.y102m.60-18-d12-1.48.I     07:57:38       07:57:38   
313672  324.y102m.60-18-d12-1.48.I     07:58:07       07:58:07   
313673  324.y102m.60-18-d12-1.48.I     07:58:40       07:58:40   
313674  324.y102m.60-18-d12-1.48.I     07:59:57       07:59:57   
313675  324.y102m.60-18-d12-1.48.I     08:01:06       08:01:06   
313676  324.y102m.60-18-d12-1.48.I     08:02:14       08:02:14   
313677  324.y102m.60-18-d12-1.48.I     08:03:34       08:03:34   
313678  324.y102m.60-18-d12-1.48.I     08:04:37       08:04:37   
313679  324.y102m.60-18-d12-1.48.I     08:05:36       08:05:36   
313680  324.y102m.60-18-d12-1.48.I     08:06:12       08:06:12   
313681  324.y102m.60-18-d12-1.48.I     08:06:50       08:06:50   
313682  324.y102m.60-18-d12-1.48.I     08:07:34       08:07:34   
313683  324.y102m.60-18-d12-1.48.I     08:08:14       08:08:14   
313684  324.y102m.60-18-d12-1.48.I     08:09:07       08:09:07   
313685  324.y102m.60-18-d12-1.48.I     08:10:00       08:10:00   
313686  324.y102m.60-18-d12-1.48.I     08:10:27       08:10:27   
...                            ...          ...            ...   
313689  324.y102m.60-18-d12-1.48.I     08:12:36       08:12:36   
313690  324.y102m.60-18-d12-1.48.I     08:14:07       08:14:07   
313691  324.y102m.60-18-d12-1.48.I     08:14:36       08:14:36   
313692  324.y102m.60-18-d12-1.48.I     08:15:09       08:15:09   
313693  324.y102m.60-18-d12-1.48.I     08:16:55       08:16:55   
313694  324.y102m.60-18-d12-1.48.I     08:17:23       08:17:23   
313695  324.y102m.60-18-d12-1.48.I     08:19:06       08:19:06   
313696  324.y102m.60-18-d12-1.48.I     08:19:58       08:19:58   
313697  324.y102m.60-18-d12-1.48.I     08:20:27       08:20:27   
313698  324.y102m.60-18-d12-1.48.I     08:21:24       08:21:24   
313699  324.y102m.60-18-d12-1.48.I     08:22:51       08:22:51   
313700  324.y102m.60-18-d12-1.48.I     08:23:46       08:23:46   
313701  324.y102m.60-18-d12-1.48.I     08:24:52       08:24:52   
313702  324.y102m.60-18-d12-1.48.I     08:26:40       08:26:40   
313703  324.y102m.60-18-d12-1.48.I     08:27:53       08:27:53   
313704  324.y102m.60-18-d12-1.48.I     08:28:21       08:28:21   
313705  324.y102m.60-18-d12-1.48.I     08:28:43       08:28:43   
313706  324.y102m.60-18-d12-1.48.I     08:29:53       08:29:53   
313707  324.y102m.60-18-d12-1.48.I     08:31:11       08:31:11   
313708  324.y102m.60-18-d12-1.48.I     08:31:58       08:31:58   
313709  324.y102m.60-18-d12-1.48.I     08:32:43       08:32:43   
313710  324.y102m.60-18-d12-1.48.I     08:33:34       08:33:34   
313711  324.y102m.60-18-d12-1.48.I     08:34:25       08:34:25   
313712  324.y102m.60-18-d12-1.48.I     08:35:22       08:35:22   
313713  324.y102m.60-18-d12-1.48.I     08:36:31       08:36:31   
313714  324.y102m.60-18-d12-1.48.I     08:37:21       08:37:21   
313715  324.y102m.60-18-d12-1.48.I     08:39:08       08:39:08   
313716  324.y102m.60-18-d12-1.48.I     08:41:08       08:41:08   
313717  324.y102m.60-18-d12-1.48.I     08:41:42       08:41:42   
3

# after check with dublin bus api manually
'324.y102m.60-18-d12-1.48.I' = 7668

In [107]:
distance[distance["stop_id"]=='gen:57102:3542:0:1']

trip_id arrival_time departure_time  \
689068   5089.y102m.60-47-d12-1.359.I     16:24:19       16:24:19   
689123   5002.y102m.60-47-d12-1.359.I     12:25:38       12:25:38   
689178   5085.y102m.60-47-d12-1.359.I     11:10:38       11:10:38   
689233   5004.y102m.60-47-d12-1.359.I     14:50:56       14:50:56   
689288   5087.y102m.60-47-d12-1.359.I     13:35:56       13:35:56   
689340  10446.y102o.60-47-d12-1.360.I     16:29:12       16:29:12   
689392  15206.y102n.60-47-d12-1.360.I     14:17:54       14:17:54   
689444  15222.y102n.60-47-d12-1.360.I     15:17:54       15:17:54   
689496  10452.y102o.60-47-d12-1.360.I     22:14:47       22:14:47   
689548  10454.y102o.60-47-d12-1.360.I     24:14:47       24:14:47   
689600  10541.y102o.60-47-d12-1.360.I     21:14:47       21:14:47   
689652  10543.y102o.60-47-d12-1.360.I     23:14:47       23:14:47   
689704  10529.y102o.60-47-d12-1.360.I     09:16:43       09:16:43   
689756  15210.y102n.60-47-d12-1.360.I     18:14:00       18:14:00   
689808  15226.y102n.60-47-d12-1.360.I     19:18:56       19:18:56   
689860   5006.y102m.60-47-d12-1.360.I     17:40:27       17:40:27   
689912   5179.y102m.60-47-d12-1.360.I     18:25:27       18:25:27   
689964  10440.y102o.60-47-d12-1.360.I     10:21:53       10:21:53   
690016  10531.y102o.60-47-d12-1.360.I     11:21:53       11:21:53   
690068  15202.y102n.60-47-d12-1.360.I     10:18:59       10:18:59   
690120  15204.y102n.60-47-d12-1.360.I     12:18:59       12:18:59   
690172  15218.y102n.60-47-d12-1.360.I     11:18:59       11:18:59   
690224  15220.y102n.60-47-d12-1.360.I     13:18:59       13:18:59   
690276   4998.y102m.60-47-d12-1.360.I     07:40:02       07:40:02   
690328   5083.y102m.60-47-d12-1.360.I     08:10:02       08:10:02   
690380   5135.y102m.60-47-d12-1.360.I     08:40:02       08:40:02   
690432  10438.y102o.60-47-d12-1.360.I     08:08:38       08:08:38   
690484   5010.y102m.60-47-d12-1.360.I     22:13:48       22:13:48   
690536   5012.y102m.60-47-d12-1.360.I     24:13:48       24:13:48   
690588   5095.y102m.60-47-d12-1.360.I     23:13:48       23:13:48   
690640  15224.y102n.60-47-d12-1.360.I     17:11:31       17:11:31   
690692  10442.y102o.60-47-d12-1.360.I     12:31:27       12:31:27   
690744  10444.y102o.60-47-d12-1.360.I     14:31:27       14:31:27   
690796  10533.y102o.60-47-d12-1.360.I     13:31:27       13:31:27   
690848   5091.y102m.60-47-d12-1.360.I     18:59:47       18:59:47   
690900   5138.y102m.60-47-d12-1.360.I     19:29:47       19:29:47   
690952   5008.y102m.60-47-d12-1.360.I     20:18:32       20:18:32   
691004   5093.y102m.60-47-d12-1.360.I     21:18:32       21:18:32   
691056  10535.y102o.60-47-d12-1.360.I     15:25:00       15:25:00   
691108  10537.y102o.60-47-d12-1.360.I     17:28:20       17:28:20   
691160  15214.y102n.60-47-d12-1.360.I     22:13:27       22:13:27   
691212  15216.y102n.60-47-d12-1.360.I     24:13:27       24:13:27   
691264  15230.y102n.60-47-d12-1.360.I     23:13:27       23:13:27   
691316   5000.y102m.60-47-d12-1.360.I     10:06:36       10:06:36   
691368   5192.y102m.60-47-d12-1.360.I     09:21:26       09:21:26   
691420  15208.y102n.60-47-d12-1.360.I     16:25:27       16:25:27   
691472  10448.y102o.60-47-d12-1.360.I     18:20:00       18:20:00   
691524  10450.y102o.60-47-d12-1.360.I     20:18:00       20:18:00   
691576  10539.y102o.60-47-d12-1.360.I     19:18:00       19:18:00   
691628  15212.y102n.60-47-d12-1.360.I     20:19:57       20:19:57   
691680  15228.y102n.60-47-d12-1.360.I     21:19:57       21:19:57   

                   stop_id  stop_sequence    stop_headsign  pickup_type  \
689068  gen:57102:3542:0:1             55   Poolbeg Street            0   
689123  gen:57102:3542:0:1             55   Poolbeg Street            0   
689178  gen:57102:3542:0:1             55   Poolbeg Street            0   
689233  gen:57102:3542:0:1             55   Poolbeg Street            0   
689288  gen:57102:3542:0:1             55   Poolbeg Street        

In [108]:
distance[distance["trip_id"]=='5089.y102m.60-47-d12-1.359.I']

trip_id arrival_time departure_time  \
689014  5089.y102m.60-47-d12-1.359.I     15:15:00       15:15:00   
689015  5089.y102m.60-47-d12-1.359.I     15:15:38       15:15:38   
689016  5089.y102m.60-47-d12-1.359.I     15:16:27       15:16:27   
689017  5089.y102m.60-47-d12-1.359.I     15:17:41       15:17:41   
689018  5089.y102m.60-47-d12-1.359.I     15:18:20       15:18:20   
689019  5089.y102m.60-47-d12-1.359.I     15:18:57       15:18:57   
689020  5089.y102m.60-47-d12-1.359.I     15:20:12       15:20:12   
689021  5089.y102m.60-47-d12-1.359.I     15:21:15       15:21:15   
689022  5089.y102m.60-47-d12-1.359.I     15:22:57       15:22:57   
689023  5089.y102m.60-47-d12-1.359.I     15:24:24       15:24:24   
689024  5089.y102m.60-47-d12-1.359.I     15:25:05       15:25:05   
689025  5089.y102m.60-47-d12-1.359.I     15:26:01       15:26:01   
689026  5089.y102m.60-47-d12-1.359.I     15:26:49       15:26:49   
689027  5089.y102m.60-47-d12-1.359.I     15:28:01       15:28:01   
689028  5089.y102m.60-47-d12-1.359.I     15:29:18       15:29:18   
689029  5089.y102m.60-47-d12-1.359.I     15:30:41       15:30:41   
689030  5089.y102m.60-47-d12-1.359.I     15:31:09       15:31:09   
689031  5089.y102m.60-47-d12-1.359.I     15:31:50       15:31:50   
689032  5089.y102m.60-47-d12-1.359.I     15:32:58       15:32:58   
689033  5089.y102m.60-47-d12-1.359.I     15:33:53       15:33:53   
689034  5089.y102m.60-47-d12-1.359.I     15:34:38       15:34:38   
689035  5089.y102m.60-47-d12-1.359.I     15:35:14       15:35:14   
689036  5089.y102m.60-47-d12-1.359.I     15:36:17       15:36:17   
689037  5089.y102m.60-47-d12-1.359.I     15:37:32       15:37:32   
689038  5089.y102m.60-47-d12-1.359.I     15:39:07       15:39:07   
689039  5089.y102m.60-47-d12-1.359.I     15:39:39       15:39:39   
689040  5089.y102m.60-47-d12-1.359.I     15:40:21       15:40:21   
689041  5089.y102m.60-47-d12-1.359.I     15:41:16       15:41:16   
689042  5089.y102m.60-47-d12-1.359.I     15:42:09       15:42:09   
689043  5089.y102m.60-47-d12-1.359.I     15:43:16       15:43:16   
689044  5089.y102m.60-47-d12-1.359.I     15:45:23       15:45:23   
689045  5089.y102m.60-47-d12-1.359.I     15:49:06       15:49:06   
689046  5089.y102m.60-47-d12-1.359.I     15:51:22       15:51:22   
689047  5089.y102m.60-47-d12-1.359.I     15:54:19       15:54:19   
689048  5089.y102m.60-47-d12-1.359.I     15:57:20       15:57:20   
689049  5089.y102m.60-47-d12-1.359.I     15:58:11       15:58:11   
689050  5089.y102m.60-47-d12-1.359.I     15:58:30       15:58:30   
689051  5089.y102m.60-47-d12-1.359.I     15:59:15       15:59:15   
689052  5089.y102m.60-47-d12-1.359.I     16:00:07       16:00:07   
689053  5089.y102m.60-47-d12-1.359.I     16:00:31       16:00:31   
689054  5089.y102m.60-47-d12-1.359.I     16:01:25       16:01:25   
689055  5089.y102m.60-47-d12-1.359.I     16:02:16       16:02:16   
689056  5089.y102m.60-47-d12-1.359.I     16:02:36       16:02:36   
689057  5089.y102m.60-47-d12-1.359.I     16:04:04       16:04:04   
689058  5089.y102m.60-47-d12-1.359.I     16:05:39       16:05:39   
689059  5089.y102m.60-47-d12-1.359.I     16:07:05       16:07:05   
689060  5089.y102m.60-47-d12-1.359.I     16:09:36       16:09:36   
689061  5089.y102m.60-47-d12-1.359.I     16:13:21       16:13:21   
689062  5089.y102m.60-47-d12-1.359.I     16:15:22       16:15:22   
689063  5089.y102m.60-47-d12-1.359.I     16:16:29       16:16:29   
689064  5089.y102m.60-47-d12-1.359.I     16:17:31       16:17:31   
689065  5089.y102m.60-47-d12-1.359.I     16:18:22       16:18:22   
689066  5089.y102m.60-47-d12-1.359.I     16:19:54       16:19:54   
689067  5089.y102m.60-47-d12-1.359.I     16:24:15       16:24:15   
689068  5089.y102m.60-47-d12-1.359.I     16:24:19       16:24:19   

                   stop_id  stop_sequence    stop_headsign  pickup_type  \
689014        8250DB005013              1   Poolbeg Street            0   
689015        8250DB005014              2   Poolbeg Street            

gen:57102:3542:0:1 2079 North Avenue Deerpark road

In [109]:
distance[distance["stop_id"]=='gen:57102:3543:0:1']

trip_id arrival_time departure_time  \
691706   5001.y102m.60-47-d12-1.362.O     10:15:00       10:15:00   
691760   5086.y102m.60-47-d12-1.362.O     11:30:00       11:30:00   
691814   5003.y102m.60-47-d12-1.362.O     12:45:00       12:45:00   
691868   5088.y102m.60-47-d12-1.362.O     14:00:00       14:00:00   
691922   5005.y102m.60-47-d12-1.363.O     15:15:00       15:15:00   
691972  10536.y102o.60-47-d12-1.363.O     15:30:00       15:30:00   
692022  15207.y102n.60-47-d12-1.363.O     14:30:00       14:30:00   
692072  15221.y102n.60-47-d12-1.363.O     13:30:00       13:30:00   
692122  10451.y102o.60-47-d12-1.363.O     20:30:00       20:30:00   
692172  10453.y102o.60-47-d12-1.363.O     22:30:00       22:30:00   
692222  10542.y102o.60-47-d12-1.363.O     21:30:00       21:30:00   
692272  10544.y102o.60-47-d12-1.363.O     23:30:00       23:30:00   
692322  10439.y102o.60-47-d12-1.363.O     08:30:00       08:30:00   
692372  15225.y102n.60-47-d12-1.363.O     17:30:00       17:30:00   
692422  15211.y102n.60-47-d12-1.363.O     18:30:00       18:30:00   
692472   5137.y102m.60-47-d12-1.363.O     17:00:00       17:00:00   
692522   5191.y102m.60-47-d12-1.363.O     17:30:00       17:30:00   
692572  10441.y102o.60-47-d12-1.363.O     10:30:00       10:30:00   
692622  10530.y102o.60-47-d12-1.363.O     09:30:00       09:30:00   
692672  15203.y102n.60-47-d12-1.363.O     10:30:00       10:30:00   
692722  15205.y102n.60-47-d12-1.363.O     12:30:00       12:30:00   
692772  15217.y102n.60-47-d12-1.363.O     09:30:00       09:30:00   
692822  15219.y102n.60-47-d12-1.363.O     11:30:00       11:30:00   
692872  10528.y102o.60-47-d12-1.363.O     07:30:00       07:30:00   
692922   5009.y102m.60-47-d12-1.363.O     20:30:00       20:30:00   
692972   5011.y102m.60-47-d12-1.363.O     22:30:00       22:30:00   
693022   5094.y102m.60-47-d12-1.363.O     21:30:00       21:30:00   
693072   5096.y102m.60-47-d12-1.363.O     23:30:00       23:30:00   
693122  15209.y102n.60-47-d12-1.363.O     16:30:00       16:30:00   
693172  10443.y102o.60-47-d12-1.363.O     12:30:00       12:30:00   
693222  10532.y102o.60-47-d12-1.363.O     11:30:00       11:30:00   
693272  10534.y102o.60-47-d12-1.363.O     13:30:00       13:30:00   
693322   5007.y102m.60-47-d12-1.363.O     18:00:00       18:00:00   
693372   5092.y102m.60-47-d12-1.363.O     19:30:00       19:30:00   
693422   5180.y102m.60-47-d12-1.363.O     18:30:00       18:30:00   
693472  10445.y102o.60-47-d12-1.363.O     14:30:00       14:30:00   
693522  10447.y102o.60-47-d12-1.363.O     16:30:00       16:30:00   
693572  15215.y102n.60-47-d12-1.363.O     22:30:00       22:30:00   
693622  15229.y102n.60-47-d12-1.363.O     21:30:00       21:30:00   
693672  15231.y102n.60-47-d12-1.363.O     23:30:00       23:30:00   
693722   5084.y102m.60-47-d12-1.363.O     08:30:00       08:30:00   
693772   5136.y102m.60-47-d12-1.363.O     09:10:00       09:10:00   
693822   5090.y102m.60-47-d12-1.363.O     16:30:00       16:30:00   
693872   5178.y102m.60-47-d12-1.363.O     16:00:00       16:00:00   
693922   4999.y102m.60-47-d12-1.363.O     07:40:00       07:40:00   
693972  15223.y102n.60-47-d12-1.363.O     15:30:00       15:30:00   
694022  10538.y102o.60-47-d12-1.363.O     17:30:00       17:30:00   
694072  10449.y102o.60-47-d12-1.363.O     18:30:00       18:30:00   
694122  10540.y102o.60-47-d12-1.363.O     19:30:00       19:30:00   
694172  15213.y102n.60-47-d12-1.363.O     20:30:00       20:30:00   
694222  15227.y102n.60-47-d12-1.363.O     19:30:00       19:30:00   

                   stop_id  stop_sequence stop_headsign  pickup_type  \
691706  gen:57102:3543:0:1              1     Belarmine            0   
691760  gen:57102:3543:0:1              1     Belarmine            0   
691814  gen:57102:3543:0:1              1     Belarmine            0   
691868  gen:57102:3543:0:1              1     Belarmine            0   
691922  gen:57102:3543:0:1              1     Belarmine            0   
691972  g

In [110]:
distance[distance["trip_id"]=='5001.y102m.60-47-d12-1.362.O']

trip_id arrival_time departure_time  \
691706  5001.y102m.60-47-d12-1.362.O     10:15:00       10:15:00   
691707  5001.y102m.60-47-d12-1.362.O     10:17:21       10:17:21   
691708  5001.y102m.60-47-d12-1.362.O     10:19:42       10:19:42   
691709  5001.y102m.60-47-d12-1.362.O     10:22:04       10:22:04   
691710  5001.y102m.60-47-d12-1.362.O     10:23:53       10:23:53   
691711  5001.y102m.60-47-d12-1.362.O     10:24:44       10:24:44   
691712  5001.y102m.60-47-d12-1.362.O     10:25:33       10:25:33   
691713  5001.y102m.60-47-d12-1.362.O     10:26:26       10:26:26   
691714  5001.y102m.60-47-d12-1.362.O     10:27:23       10:27:23   
691715  5001.y102m.60-47-d12-1.362.O     10:29:07       10:29:07   
691716  5001.y102m.60-47-d12-1.362.O     10:30:13       10:30:13   
691717  5001.y102m.60-47-d12-1.362.O     10:30:45       10:30:45   
691718  5001.y102m.60-47-d12-1.362.O     10:31:34       10:31:34   
691719  5001.y102m.60-47-d12-1.362.O     10:32:12       10:32:12   
691720  5001.y102m.60-47-d12-1.362.O     10:32:46       10:32:46   
691721  5001.y102m.60-47-d12-1.362.O     10:33:49       10:33:49   
691722  5001.y102m.60-47-d12-1.362.O     10:35:23       10:35:23   
691723  5001.y102m.60-47-d12-1.362.O     10:36:03       10:36:03   
691724  5001.y102m.60-47-d12-1.362.O     10:36:47       10:36:47   
691725  5001.y102m.60-47-d12-1.362.O     10:37:59       10:37:59   
691726  5001.y102m.60-47-d12-1.362.O     10:38:40       10:38:40   
691727  5001.y102m.60-47-d12-1.362.O     10:40:58       10:40:58   
691728  5001.y102m.60-47-d12-1.362.O     10:42:44       10:42:44   
691729  5001.y102m.60-47-d12-1.362.O     10:43:26       10:43:26   
691730  5001.y102m.60-47-d12-1.362.O     10:44:14       10:44:14   
691731  5001.y102m.60-47-d12-1.362.O     10:45:22       10:45:22   
691732  5001.y102m.60-47-d12-1.362.O     10:46:27       10:46:27   
691733  5001.y102m.60-47-d12-1.362.O     10:47:27       10:47:27   
691734  5001.y102m.60-47-d12-1.362.O     10:48:44       10:48:44   
691735  5001.y102m.60-47-d12-1.362.O     10:49:29       10:49:29   
691736  5001.y102m.60-47-d12-1.362.O     10:50:23       10:50:23   
691737  5001.y102m.60-47-d12-1.362.O     10:51:11       10:51:11   
691738  5001.y102m.60-47-d12-1.362.O     10:51:59       10:51:59   
691739  5001.y102m.60-47-d12-1.362.O     10:52:57       10:52:57   
691740  5001.y102m.60-47-d12-1.362.O     10:54:37       10:54:37   
691741  5001.y102m.60-47-d12-1.362.O     10:56:27       10:56:27   
691742  5001.y102m.60-47-d12-1.362.O     10:57:03       10:57:03   
691743  5001.y102m.60-47-d12-1.362.O     10:58:03       10:58:03   
691744  5001.y102m.60-47-d12-1.362.O     10:58:37       10:58:37   
691745  5001.y102m.60-47-d12-1.362.O     10:59:28       10:59:28   
691746  5001.y102m.60-47-d12-1.362.O     11:00:14       11:00:14   
691747  5001.y102m.60-47-d12-1.362.O     11:01:02       11:01:02   
691748  5001.y102m.60-47-d12-1.362.O     11:02:01       11:02:01   
691749  5001.y102m.60-47-d12-1.362.O     11:03:29       11:03:29   
691750  5001.y102m.60-47-d12-1.362.O     11:04:50       11:04:50   
691751  5001.y102m.60-47-d12-1.362.O     11:06:18       11:06:18   
691752  5001.y102m.60-47-d12-1.362.O     11:07:10       11:07:10   
691753  5001.y102m.60-47-d12-1.362.O     11:08:00       11:08:00   
691754  5001.y102m.60-47-d12-1.362.O     11:09:04       11:09:04   
691755  5001.y102m.60-47-d12-1.362.O     11:09:46       11:09:46   
691756  5001.y102m.60-47-d12-1.362.O     11:10:48       11:10:48   
691757  5001.y102m.60-47-d12-1.362.O     11:12:40       11:12:40   
691758  5001.y102m.60-47-d12-1.362.O     11:13:15       11:13:15   
691759  5001.y102m.60-47-d12-1.362.O     11:13:49       11:13:49   

                   stop_id  stop_sequence stop_headsign  pickup_type  \
691706  gen:57102:3543:0:1              1     Belarmine            0   
691707        8220DB007564              2     Belarmine            0   
691708        8220DB000340              3     Belarmine            0   


issue: Google show it departure from a new stop, but Dublin bus result still only show the result from 7564

In [111]:
distance[distance["stop_id"]=='gen:57102:3607:0:1']

trip_id arrival_time departure_time  \
774136   6313.y102m.60-68-d12-1.407.I     07:34:54       07:34:54   
774209  11997.y102o.60-68-d12-1.407.I     07:20:19       07:20:19   
774278   6323.y102m.60-68-d12-1.408.I     06:55:34       06:55:34   
774347   6329.y102m.60-68-d12-1.408.I     16:04:31       16:04:31   
774416  12012.y102o.60-68-d12-1.408.I     14:08:39       14:08:39   
774485  12026.y102o.60-68-d12-1.408.I     15:08:39       15:08:39   
774554  12060.y102o.60-68-d12-1.408.I     13:08:39       13:08:39   
774623  12062.y102o.60-68-d12-1.408.I     15:58:07       15:58:07   
774692  12064.y102o.60-68-d12-1.408.I     18:58:07       18:58:07   
774761   6316.y102m.60-68-d12-1.408.I     12:06:21       12:06:21   
774830   6327.y102m.60-68-d12-1.408.I     13:06:21       13:06:21   
774899   6338.y102m.60-68-d12-1.408.I     11:06:21       11:06:21   
774968   6234.y102m.60-68-d12-1.408.I     08:18:54       08:18:54   
775037  12010.y102o.60-68-d12-1.408.I     10:41:15       10:41:15   
775106  12022.y102o.60-68-d12-1.408.I     08:46:15       08:46:15   
775175  12024.y102o.60-68-d12-1.408.I     12:12:02       12:12:02   
775244   6318.y102m.60-68-d12-1.408.I     15:05:37       15:05:37   
775313   6340.y102m.60-68-d12-1.408.I     14:05:37       14:05:37   
775382  12016.y102o.60-68-d12-1.408.I     19:56:31       19:56:31   
775451  12030.y102o.60-68-d12-1.408.I     20:56:31       20:56:31   
775520   6331.y102m.60-68-d12-1.408.I     19:22:35       19:22:35   
775589   6322.y102m.60-68-d12-1.408.I     21:10:30       21:10:30   
775658   6344.y102m.60-68-d12-1.408.I     20:10:30       20:10:30   
775727   6302.y102m.60-68-d12-1.408.I     09:10:37       09:10:37   
775796   6320.y102m.60-68-d12-1.409.I     18:30:17       18:30:17   
775865  12014.y102o.60-68-d12-1.409.I     17:03:10       17:03:10   
775934  12028.y102o.60-68-d12-1.409.I     18:03:10       18:03:10   
776003  11999.y102o.60-68-d12-1.409.I     10:19:47       10:19:47   
776072   6325.y102m.60-68-d12-1.409.I     10:18:46       10:18:46   
776141   6342.y102m.60-68-d12-1.409.I     17:17:13       17:17:13   
...                               ...          ...            ...   
780022  16496.y102n.60-69-d12-1.416.I     12:49:25       12:49:25   
780083  16500.y102n.60-69-d12-1.416.I     15:24:25       15:24:25   
780144  12007.y102o.60-69-d12-1.416.I     22:17:11       22:17:11   
780205  12041.y102o.60-69-d12-1.416.I     23:57:11       23:57:11   
780266  12053.y102o.60-69-d12-1.416.I     22:57:11       22:57:11   
780327  16524.y102n.60-69-d12-1.416.I     22:52:12       22:52:12   
780388  12008.y102o.60-69-d12-1.416.I     07:47:05       07:47:05   
780449  12031.y102o.60-69-d12-1.416.I     08:37:05       08:37:05   
780510  12043.y102o.60-69-d12-1.416.I     08:22:05       08:22:05   
780571  12056.y102o.60-69-d12-1.416.I     07:07:05       07:07:05   
781655   6231.y102m.60-69-d12-1.419.I     06:58:27       06:58:27   
781716   6291.y102m.60-69-d12-1.419.I     15:33:57       15:33:57   
781777   6355.y102m.60-69-d12-1.419.I     17:47:41       17:47:41   
781838   6289.y102m.60-69-d12-1.419.I     12:32:18       12:32:18   
781899   6351.y102m.60-69-d12-1.419.I     11:32:18       11:32:18   
781960   6294.y102m.60-69-d12-1.419.I     08:31:19       08:31:19   
782021   6336.y102m.60-69-d12-1.419.I     08:01:19       08:01:19   
782082   6296.y102m.60-69-d12-1.419.I     13:32:49       13:32:49   
782143   6353.y102m.60-69-d12-1.419.I     14:32:49       14:32:49   
782204   6308.y102m.60-69-d12-1.419.I     24:02:35       24:02:35   
782265   6333.y102m.60-69-d12-1.419.I     22:02:35       22:02:35   
782326   6359.y102m.60-69-d12-1.419.I     23:02:35       23:02:35   
782387   6304.y102m.60-69-d12-1.419.I     18:45:59       18:45:59   
782448   6306.y102m.60-69-d12-1.419.I     21:09:32       21:09:32   
782509   6310.y102m.60-69-d12-1.419.I     19:24:32       19:24:32   
782570   6357.y102m.60-69-d12-1.419.I     20:24:32       20:24:32   
782631   6233.y102m.60-69-d1

In [112]:
distance[distance["trip_id"]=='6313.y102m.60-68-d12-1.407.I']

trip_id arrival_time departure_time  \
774064  6313.y102m.60-68-d12-1.407.I     06:30:00       06:30:00   
774065  6313.y102m.60-68-d12-1.407.I     06:30:42       06:30:42   
774066  6313.y102m.60-68-d12-1.407.I     06:31:53       06:31:53   
774067  6313.y102m.60-68-d12-1.407.I     06:32:50       06:32:50   
774068  6313.y102m.60-68-d12-1.407.I     06:33:25       06:33:25   
774069  6313.y102m.60-68-d12-1.407.I     06:33:55       06:33:55   
774070  6313.y102m.60-68-d12-1.407.I     06:34:18       06:34:18   
774071  6313.y102m.60-68-d12-1.407.I     06:34:35       06:34:35   
774072  6313.y102m.60-68-d12-1.407.I     06:34:52       06:34:52   
774073  6313.y102m.60-68-d12-1.407.I     06:35:08       06:35:08   
774074  6313.y102m.60-68-d12-1.407.I     06:35:22       06:35:22   
774075  6313.y102m.60-68-d12-1.407.I     06:35:48       06:35:48   
774076  6313.y102m.60-68-d12-1.407.I     06:35:56       06:35:56   
774077  6313.y102m.60-68-d12-1.407.I     06:36:49       06:36:49   
774078  6313.y102m.60-68-d12-1.407.I     06:37:22       06:37:22   
774079  6313.y102m.60-68-d12-1.407.I     06:37:41       06:37:41   
774080  6313.y102m.60-68-d12-1.407.I     06:38:10       06:38:10   
774081  6313.y102m.60-68-d12-1.407.I     06:38:19       06:38:19   
774082  6313.y102m.60-68-d12-1.407.I     06:39:09       06:39:09   
774083  6313.y102m.60-68-d12-1.407.I     06:39:34       06:39:34   
774084  6313.y102m.60-68-d12-1.407.I     06:39:48       06:39:48   
774085  6313.y102m.60-68-d12-1.407.I     06:40:20       06:40:20   
774086  6313.y102m.60-68-d12-1.407.I     06:41:33       06:41:33   
774087  6313.y102m.60-68-d12-1.407.I     06:41:59       06:41:59   
774088  6313.y102m.60-68-d12-1.407.I     06:42:48       06:42:48   
774089  6313.y102m.60-68-d12-1.407.I     06:43:34       06:43:34   
774090  6313.y102m.60-68-d12-1.407.I     06:44:06       06:44:06   
774091  6313.y102m.60-68-d12-1.407.I     06:44:42       06:44:42   
774092  6313.y102m.60-68-d12-1.407.I     06:45:56       06:45:56   
774093  6313.y102m.60-68-d12-1.407.I     06:46:31       06:46:31   
...                              ...          ...            ...   
774107  6313.y102m.60-68-d12-1.407.I     06:59:32       06:59:32   
774108  6313.y102m.60-68-d12-1.407.I     07:00:13       07:00:13   
774109  6313.y102m.60-68-d12-1.407.I     07:00:37       07:00:37   
774110  6313.y102m.60-68-d12-1.407.I     07:01:12       07:01:12   
774111  6313.y102m.60-68-d12-1.407.I     07:02:03       07:02:03   
774112  6313.y102m.60-68-d12-1.407.I     07:03:01       07:03:01   
774113  6313.y102m.60-68-d12-1.407.I     07:04:09       07:04:09   
774114  6313.y102m.60-68-d12-1.407.I     07:04:40       07:04:40   
774115  6313.y102m.60-68-d12-1.407.I     07:05:44       07:05:44   
774116  6313.y102m.60-68-d12-1.407.I     07:06:58       07:06:58   
774117  6313.y102m.60-68-d12-1.407.I     07:08:54       07:08:54   
774118  6313.y102m.60-68-d12-1.407.I     07:09:53       07:09:53   
774119  6313.y102m.60-68-d12-1.407.I     07:11:06       07:11:06   
774120  6313.y102m.60-68-d12-1.407.I     07:12:06       07:12:06   
774121  6313.y102m.60-68-d12-1.407.I     07:13:16       07:13:16   
774122  6313.y102m.60-68-d12-1.407.I     07:14:41       07:14:41   
774123  6313.y102m.60-68-d12-1.407.I     07:15:24       07:15:24   
774124  6313.y102m.60-68-d12-1.407.I     07:16:44       07:16:44   
774125  6313.y102m.60-68-d12-1.407.I     07:17:15       07:17:15   
774126  6313.y102m.60-68-d12-1.407.I     07:17:46       07:17:46   
774127  6313.y102m.60-68-d12-1.407.I     07:19:02       07:19:02   
774128  6313.y102m.60-68-d12-1.407.I     07:20:21       07:20:21   
774129  6313.y102m.60-68-d12-1.407.I     07:21:24       07:21:24   
774130  6313.y102m.60-68-d12-1.407.I     07:22:34       07:22:34   
774131  6313.y102m.60-68-d12-1.407.I     07:24:32       07:24:32   
774132  6313.y102m.60-68-d12-1.407.I     07:25:27       07:25:27   
774133  6313.y102m.60-68-d12-1.407.I     07:27:40       07:27:40   
774134  6313.y102

gen:57102:3607:0:1 7665 Poolbeg Street Hawkin House

In [113]:
distance[distance["stop_id"]=='gen:57102:3606:0:1']

trip_id arrival_time departure_time  \
873212  6093.y102m.60-7D-d12-1.183.I     05:21:06       05:21:06   

                   stop_id  stop_sequence     stop_headsign  pickup_type  \
873212  gen:57102:3606:0:1              3   Mountjoy Square            0   

        drop_off_type  shape_dist_traveled          trip1 trip2 trip3  \
873212              0           887.960579  6093.y102m.60    7D   d12   

          trip4           shape_id new_stop_id  
873212  1.183.I  60-7D-d12-1.183.I           1

In [114]:
distance[distance["trip_id"]=='6093.y102m.60-7D-d12-1.183.I']

trip_id arrival_time departure_time  \
873210  6093.y102m.60-7D-d12-1.183.I     05:20:00       05:20:00   
873211  6093.y102m.60-7D-d12-1.183.I     05:20:41       05:20:41   
873212  6093.y102m.60-7D-d12-1.183.I     05:21:06       05:21:06   
873213  6093.y102m.60-7D-d12-1.183.I     05:21:45       05:21:45   
873214  6093.y102m.60-7D-d12-1.183.I     05:22:05       05:22:05   
873215  6093.y102m.60-7D-d12-1.183.I     05:22:28       05:22:28   
873216  6093.y102m.60-7D-d12-1.183.I     05:24:46       05:24:46   
873217  6093.y102m.60-7D-d12-1.183.I     05:25:14       05:25:14   
873218  6093.y102m.60-7D-d12-1.183.I     05:25:31       05:25:31   
873219  6093.y102m.60-7D-d12-1.183.I     05:25:50       05:25:50   
873220  6093.y102m.60-7D-d12-1.183.I     05:26:04       05:26:04   
873221  6093.y102m.60-7D-d12-1.183.I     05:26:42       05:26:42   
873222  6093.y102m.60-7D-d12-1.183.I     05:26:54       05:26:54   
873223  6093.y102m.60-7D-d12-1.183.I     05:27:28       05:27:28   
873224  6093.y102m.60-7D-d12-1.183.I     05:27:49       05:27:49   
873225  6093.y102m.60-7D-d12-1.183.I     05:28:13       05:28:13   
873226  6093.y102m.60-7D-d12-1.183.I     05:28:33       05:28:33   
873227  6093.y102m.60-7D-d12-1.183.I     05:29:06       05:29:06   
873228  6093.y102m.60-7D-d12-1.183.I     05:31:33       05:31:33   
873229  6093.y102m.60-7D-d12-1.183.I     05:32:15       05:32:15   
873230  6093.y102m.60-7D-d12-1.183.I     05:32:46       05:32:46   
873231  6093.y102m.60-7D-d12-1.183.I     05:33:18       05:33:18   
873232  6093.y102m.60-7D-d12-1.183.I     05:33:56       05:33:56   
873233  6093.y102m.60-7D-d12-1.183.I     05:34:10       05:34:10   
873234  6093.y102m.60-7D-d12-1.183.I     05:34:35       05:34:35   
873235  6093.y102m.60-7D-d12-1.183.I     05:34:56       05:34:56   
873236  6093.y102m.60-7D-d12-1.183.I     05:35:52       05:35:52   
873237  6093.y102m.60-7D-d12-1.183.I     05:36:10       05:36:10   
873238  6093.y102m.60-7D-d12-1.183.I     05:36:31       05:36:31   
873239  6093.y102m.60-7D-d12-1.183.I     05:37:03       05:37:03   
...                              ...          ...            ...   
873261  6093.y102m.60-7D-d12-1.183.I     05:50:43       05:50:43   
873262  6093.y102m.60-7D-d12-1.183.I     05:50:59       05:50:59   
873263  6093.y102m.60-7D-d12-1.183.I     05:51:17       05:51:17   
873264  6093.y102m.60-7D-d12-1.183.I     05:51:34       05:51:34   
873265  6093.y102m.60-7D-d12-1.183.I     05:52:02       05:52:02   
873266  6093.y102m.60-7D-d12-1.183.I     05:52:16       05:52:16   
873267  6093.y102m.60-7D-d12-1.183.I     05:52:41       05:52:41   
873268  6093.y102m.60-7D-d12-1.183.I     05:53:04       05:53:04   
873269  6093.y102m.60-7D-d12-1.183.I     05:53:29       05:53:29   
873270  6093.y102m.60-7D-d12-1.183.I     05:54:09       05:54:09   
873271  6093.y102m.60-7D-d12-1.183.I     05:55:10       05:55:10   
873272  6093.y102m.60-7D-d12-1.183.I     05:55:33       05:55:33   
873273  6093.y102m.60-7D-d12-1.183.I     05:56:19       05:56:19   
873274  6093.y102m.60-7D-d12-1.183.I     05:59:25       05:59:25   
873275  6093.y102m.60-7D-d12-1.183.I     05:59:51       05:59:51   
873276  6093.y102m.60-7D-d12-1.183.I     06:00:55       06:00:55   
873277  6093.y102m.60-7D-d12-1.183.I     06:01:37       06:01:37   
873278  6093.y102m.60-7D-d12-1.183.I     06:02:08       06:02:08   
873279  6093.y102m.60-7D-d12-1.183.I     06:02:38       06:02:38   
873280  6093.y102m.60-7D-d12-1.183.I     06:03:09       06:03:09   
873281  6093.y102m.60-7D-d12-1.183.I     06:03:42       06:03:42   
873282  6093.y102m.60-7D-d12-1.183.I     06:04:36       06:04:36   
873283  6093.y102m.60-7D-d12-1.183.I     06:05:38       06:05:38   
873284  6093.y102m.60-7D-d12-1.183.I     06:06:53       06:06:53   
873285  6093.y102m.60-7D-d12-1.183.I     06:07:33       06:07:33   
873286  6093.y102m.60-7D-d12-1.183.I     06:08:34       06:08:34   
873287  6093.y102m.60-7D-d12-1.183.I     06:09:48       06:09:48   
873288  6093.y102

7667 gen:57102:3606:0:1 Barnhill Rd
7668 gen:57102:5245:0:1 
7665 gen:57102:3607:0:1 Poolbeg Street Hawkin House

In [115]:
distance.loc[distance["stop_id"]=="gen:57102:3606:0:1","new_stop_id"] = 7667
distance.loc[distance["stop_id"]=="gen:57102:5245:0:1","new_stop_id"]  = 7668
distance.loc[distance["stop_id"]=="gen:57102:3607:0:1","new_stop_id"] = 7665

In [116]:
distance[distance["stop_id"]=="gen:57102:3606:0:1"]

trip_id arrival_time departure_time  \
873212  6093.y102m.60-7D-d12-1.183.I     05:21:06       05:21:06   

                   stop_id  stop_sequence     stop_headsign  pickup_type  \
873212  gen:57102:3606:0:1              3   Mountjoy Square            0   

        drop_off_type  shape_dist_traveled          trip1 trip2 trip3  \
873212              0           887.960579  6093.y102m.60    7D   d12   

          trip4           shape_id new_stop_id  
873212  1.183.I  60-7D-d12-1.183.I        7667

In [117]:
distance.sample(10)

trip_id arrival_time departure_time  \
867449   11435.y102o.60-7A-d12-1.176.I     13:03:23       13:03:23   
577075    3264.y102m.60-40-d12-1.295.I     07:54:42       07:54:42   
779522   16506.y102n.60-69-d12-1.416.I     16:53:30       16:53:30   
715449     3218.y102m.60-59-d12-1.65.I     12:54:11       12:54:11   
824080  11807.y102o.60-757-d12-1.168.I     05:18:03       05:18:03   
659972   5041.y102m.60-46A-d12-1.349.I     11:23:10       11:23:10   
792501    17114.y102n.60-7-d12-1.172.O     21:49:15       21:49:15   
284950     1327.y102m.60-17-d12-1.37.O     09:30:14       09:30:14   
164349  17334.y102n.60-145-d12-1.475.O     22:07:01       22:07:01   
882170    9293.y102o.60-83-d12-1.434.I     10:06:44       10:06:44   

             stop_id  stop_sequence     stop_headsign  pickup_type  \
867449  8220DB000483             51   Mountjoy Square            0   
577075  8230DB002686             15       Charlestown            0   
779522  8220DB007435             50    Poolbeg Street            0   
715449  8250DB003105              7     Dun Laoghaire            0   
824080  8220DB007397             10     Charlotte Way            1   
659972  8250DB002046              8        Phoenix Pk            0   
792501  8250DB003038             32       Brides Glen            0   
284950  8230DB001303             29    Blackrock DART            0   
164349  8250DB004124             51      Ballywaltrim            0   
882170  8220DB007426             53        Harristown            0   

        drop_off_type  shape_dist_traveled           trip1 trip2 trip3  \
867449              0         17536.768070  11435.y102o.60    7A   d12   
577075              0          5758.670554   3264.y102m.60    40   d12   
779522              0         18440.198342  16506.y102n.60    69   d12   
715449              0          1928.327547   3218.y102m.60    59   d12   
824080              0         14504.357458  11807.y102o.60   757   d12   
659972              0          1945.897360   5041.y102m.60   46A   d12   
792501              0         10733.315760  17114.y102n.60     7   d12   
284950              0          7513.493058   1327.y102m.60    17   d12   
164349              0         22610.756249  17334.y102n.60   145   d12   
882170              0         15172.731036   9293.y102o.60    83   d12   

          trip4            shape_id new_stop_id  
867449  1.176.I   60-7A-d12-1.176.I         483  
577075  1.295.I   60-40-d12-1.295.I        2686  
779522  1.416.I   60-69-d12-1.416.I        7435  
715449   1.65.I    60-59-d12-1.65.I        3105  
824080  1.168.I  60-757-d12-1.168.I        7397  
659972  1.349.I  60-46A-d12-1.349.I        2046  
792501  1.172.O    60-7-d12-1.172.O        3038  
284950   1.37.O    60-17-d12-1.37.O        1303  
164349  1.475.O  60-145-d12-1.475.O        4124  
882170  1.434.I   60-83-d12-1.434.I        7426

### check gen:57102:3542:0:1,gen:57102:3543:0:1

In [118]:
distance[distance["stop_id"]=="gen:57102:3542:0:1"].trip2.unique()

array(['47'], dtype=object)

In [119]:
distance[distance["stop_id"]=="gen:57102:3542:0:1"]

trip_id arrival_time departure_time  \
689068   5089.y102m.60-47-d12-1.359.I     16:24:19       16:24:19   
689123   5002.y102m.60-47-d12-1.359.I     12:25:38       12:25:38   
689178   5085.y102m.60-47-d12-1.359.I     11:10:38       11:10:38   
689233   5004.y102m.60-47-d12-1.359.I     14:50:56       14:50:56   
689288   5087.y102m.60-47-d12-1.359.I     13:35:56       13:35:56   
689340  10446.y102o.60-47-d12-1.360.I     16:29:12       16:29:12   
689392  15206.y102n.60-47-d12-1.360.I     14:17:54       14:17:54   
689444  15222.y102n.60-47-d12-1.360.I     15:17:54       15:17:54   
689496  10452.y102o.60-47-d12-1.360.I     22:14:47       22:14:47   
689548  10454.y102o.60-47-d12-1.360.I     24:14:47       24:14:47   
689600  10541.y102o.60-47-d12-1.360.I     21:14:47       21:14:47   
689652  10543.y102o.60-47-d12-1.360.I     23:14:47       23:14:47   
689704  10529.y102o.60-47-d12-1.360.I     09:16:43       09:16:43   
689756  15210.y102n.60-47-d12-1.360.I     18:14:00       18:14:00   
689808  15226.y102n.60-47-d12-1.360.I     19:18:56       19:18:56   
689860   5006.y102m.60-47-d12-1.360.I     17:40:27       17:40:27   
689912   5179.y102m.60-47-d12-1.360.I     18:25:27       18:25:27   
689964  10440.y102o.60-47-d12-1.360.I     10:21:53       10:21:53   
690016  10531.y102o.60-47-d12-1.360.I     11:21:53       11:21:53   
690068  15202.y102n.60-47-d12-1.360.I     10:18:59       10:18:59   
690120  15204.y102n.60-47-d12-1.360.I     12:18:59       12:18:59   
690172  15218.y102n.60-47-d12-1.360.I     11:18:59       11:18:59   
690224  15220.y102n.60-47-d12-1.360.I     13:18:59       13:18:59   
690276   4998.y102m.60-47-d12-1.360.I     07:40:02       07:40:02   
690328   5083.y102m.60-47-d12-1.360.I     08:10:02       08:10:02   
690380   5135.y102m.60-47-d12-1.360.I     08:40:02       08:40:02   
690432  10438.y102o.60-47-d12-1.360.I     08:08:38       08:08:38   
690484   5010.y102m.60-47-d12-1.360.I     22:13:48       22:13:48   
690536   5012.y102m.60-47-d12-1.360.I     24:13:48       24:13:48   
690588   5095.y102m.60-47-d12-1.360.I     23:13:48       23:13:48   
690640  15224.y102n.60-47-d12-1.360.I     17:11:31       17:11:31   
690692  10442.y102o.60-47-d12-1.360.I     12:31:27       12:31:27   
690744  10444.y102o.60-47-d12-1.360.I     14:31:27       14:31:27   
690796  10533.y102o.60-47-d12-1.360.I     13:31:27       13:31:27   
690848   5091.y102m.60-47-d12-1.360.I     18:59:47       18:59:47   
690900   5138.y102m.60-47-d12-1.360.I     19:29:47       19:29:47   
690952   5008.y102m.60-47-d12-1.360.I     20:18:32       20:18:32   
691004   5093.y102m.60-47-d12-1.360.I     21:18:32       21:18:32   
691056  10535.y102o.60-47-d12-1.360.I     15:25:00       15:25:00   
691108  10537.y102o.60-47-d12-1.360.I     17:28:20       17:28:20   
691160  15214.y102n.60-47-d12-1.360.I     22:13:27       22:13:27   
691212  15216.y102n.60-47-d12-1.360.I     24:13:27       24:13:27   
691264  15230.y102n.60-47-d12-1.360.I     23:13:27       23:13:27   
691316   5000.y102m.60-47-d12-1.360.I     10:06:36       10:06:36   
691368   5192.y102m.60-47-d12-1.360.I     09:21:26       09:21:26   
691420  15208.y102n.60-47-d12-1.360.I     16:25:27       16:25:27   
691472  10448.y102o.60-47-d12-1.360.I     18:20:00       18:20:00   
691524  10450.y102o.60-47-d12-1.360.I     20:18:00       20:18:00   
691576  10539.y102o.60-47-d12-1.360.I     19:18:00       19:18:00   
691628  15212.y102n.60-47-d12-1.360.I     20:19:57       20:19:57   
691680  15228.y102n.60-47-d12-1.360.I     21:19:57       21:19:57   

                   stop_id  stop_sequence    stop_headsign  pickup_type  \
689068  gen:57102:3542:0:1             55   Poolbeg Street            0   
689123  gen:57102:3542:0:1             55   Poolbeg Street            0   
689178  gen:57102:3542:0:1             55   Poolbeg Street            0   
689233  gen:57102:3542:0:1             55   Poolbeg Street            0   
689288  gen:57102:3542:0:1             55   Poolbeg Street        

In [120]:
distance[distance["stop_id"]=="gen:57102:3543:0:1"].trip2.unique()

array(['47'], dtype=object)

It seems that these two new stops only are discovered in the route 47

In [121]:
distance[(distance["trip2"]=='47')&(distance["stop_sequence"] == 1)].stop_id.unique()

array(['8250DB005013', '8220DB000763', 'gen:57102:3543:0:1'], dtype=object)

historic data is "763, 5013, 337, 7662"

In [122]:
distance_47 = distance [distance["trip2"]=='47']

In [123]:
distance_47.groupby(["trip_id"]).stop_sequence.count().unique()

array([52, 50, 25, 54, 55], dtype=int64)

In [124]:
distance_47[distance_47["new_stop_id"] == '337']

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled, trip1, trip2, trip3, trip4, shape_id, new_stop_id]
Index: []

we can have the conclusion that the gen:gen:57102:3543:0:1 supposed to be the bus stop 337?

In [125]:
distance.loc[distance["stop_id"]=="gen:57102:3606:0:1","new_stop_id"] = 7667

In [126]:
def get_destinationstop(group):
    group.sort_values(['stop_sequence'],ascending=False)
    max_sequence_row = group.ix[group['stop_sequence'].idxmax()]
    group["route_end_stop"] = max_sequence_row.stop_id
    return group

In [127]:
distance_47 = distance_47.groupby(["trip_id"]).apply(get_destinationstop)

C:\Users\Di\Anaconda3\envs\bashi\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


In [128]:
distance_47.route_end_stop.unique()

array(['gen:57102:3542:0:1', '8250DB005016'], dtype=object)

In [129]:
distance_47[distance_47["stop_id"] == 'gen:57102:3542:0:1']

trip_id arrival_time departure_time  \
689068   5089.y102m.60-47-d12-1.359.I     16:24:19       16:24:19   
689123   5002.y102m.60-47-d12-1.359.I     12:25:38       12:25:38   
689178   5085.y102m.60-47-d12-1.359.I     11:10:38       11:10:38   
689233   5004.y102m.60-47-d12-1.359.I     14:50:56       14:50:56   
689288   5087.y102m.60-47-d12-1.359.I     13:35:56       13:35:56   
689340  10446.y102o.60-47-d12-1.360.I     16:29:12       16:29:12   
689392  15206.y102n.60-47-d12-1.360.I     14:17:54       14:17:54   
689444  15222.y102n.60-47-d12-1.360.I     15:17:54       15:17:54   
689496  10452.y102o.60-47-d12-1.360.I     22:14:47       22:14:47   
689548  10454.y102o.60-47-d12-1.360.I     24:14:47       24:14:47   
689600  10541.y102o.60-47-d12-1.360.I     21:14:47       21:14:47   
689652  10543.y102o.60-47-d12-1.360.I     23:14:47       23:14:47   
689704  10529.y102o.60-47-d12-1.360.I     09:16:43       09:16:43   
689756  15210.y102n.60-47-d12-1.360.I     18:14:00       18:14:00   
689808  15226.y102n.60-47-d12-1.360.I     19:18:56       19:18:56   
689860   5006.y102m.60-47-d12-1.360.I     17:40:27       17:40:27   
689912   5179.y102m.60-47-d12-1.360.I     18:25:27       18:25:27   
689964  10440.y102o.60-47-d12-1.360.I     10:21:53       10:21:53   
690016  10531.y102o.60-47-d12-1.360.I     11:21:53       11:21:53   
690068  15202.y102n.60-47-d12-1.360.I     10:18:59       10:18:59   
690120  15204.y102n.60-47-d12-1.360.I     12:18:59       12:18:59   
690172  15218.y102n.60-47-d12-1.360.I     11:18:59       11:18:59   
690224  15220.y102n.60-47-d12-1.360.I     13:18:59       13:18:59   
690276   4998.y102m.60-47-d12-1.360.I     07:40:02       07:40:02   
690328   5083.y102m.60-47-d12-1.360.I     08:10:02       08:10:02   
690380   5135.y102m.60-47-d12-1.360.I     08:40:02       08:40:02   
690432  10438.y102o.60-47-d12-1.360.I     08:08:38       08:08:38   
690484   5010.y102m.60-47-d12-1.360.I     22:13:48       22:13:48   
690536   5012.y102m.60-47-d12-1.360.I     24:13:48       24:13:48   
690588   5095.y102m.60-47-d12-1.360.I     23:13:48       23:13:48   
690640  15224.y102n.60-47-d12-1.360.I     17:11:31       17:11:31   
690692  10442.y102o.60-47-d12-1.360.I     12:31:27       12:31:27   
690744  10444.y102o.60-47-d12-1.360.I     14:31:27       14:31:27   
690796  10533.y102o.60-47-d12-1.360.I     13:31:27       13:31:27   
690848   5091.y102m.60-47-d12-1.360.I     18:59:47       18:59:47   
690900   5138.y102m.60-47-d12-1.360.I     19:29:47       19:29:47   
690952   5008.y102m.60-47-d12-1.360.I     20:18:32       20:18:32   
691004   5093.y102m.60-47-d12-1.360.I     21:18:32       21:18:32   
691056  10535.y102o.60-47-d12-1.360.I     15:25:00       15:25:00   
691108  10537.y102o.60-47-d12-1.360.I     17:28:20       17:28:20   
691160  15214.y102n.60-47-d12-1.360.I     22:13:27       22:13:27   
691212  15216.y102n.60-47-d12-1.360.I     24:13:27       24:13:27   
691264  15230.y102n.60-47-d12-1.360.I     23:13:27       23:13:27   
691316   5000.y102m.60-47-d12-1.360.I     10:06:36       10:06:36   
691368   5192.y102m.60-47-d12-1.360.I     09:21:26       09:21:26   
691420  15208.y102n.60-47-d12-1.360.I     16:25:27       16:25:27   
691472  10448.y102o.60-47-d12-1.360.I     18:20:00       18:20:00   
691524  10450.y102o.60-47-d12-1.360.I     20:18:00       20:18:00   
691576  10539.y102o.60-47-d12-1.360.I     19:18:00       19:18:00   
691628  15212.y102n.60-47-d12-1.360.I     20:19:57       20:19:57   
691680  15228.y102n.60-47-d12-1.360.I     21:19:57       21:19:57   

                   stop_id  stop_sequence    stop_headsign  pickup_type  \
689068  gen:57102:3542:0:1             55   Poolbeg Street            0   
689123  gen:57102:3542:0:1             55   Poolbeg Street            0   
689178  gen:57102:3542:0:1             55   Poolbeg Street            0   
689233  gen:57102:3542:0:1             55   Poolbeg Street            0   
689288  gen:57102:3542:0:1             55   Poolbeg Street        

In [130]:
distance_47[distance_47['trip_id']=="15202.y102n.60-47-d12-1.360.I"]

trip_id arrival_time departure_time  \
690017  15202.y102n.60-47-d12-1.360.I     09:30:00       09:30:00   
690018  15202.y102n.60-47-d12-1.360.I     09:30:40       09:30:40   
690019  15202.y102n.60-47-d12-1.360.I     09:31:31       09:31:31   
690020  15202.y102n.60-47-d12-1.360.I     09:32:50       09:32:50   
690021  15202.y102n.60-47-d12-1.360.I     09:33:29       09:33:29   
690022  15202.y102n.60-47-d12-1.360.I     09:34:15       09:34:15   
690023  15202.y102n.60-47-d12-1.360.I     09:35:27       09:35:27   
690024  15202.y102n.60-47-d12-1.360.I     09:36:28       09:36:28   
690025  15202.y102n.60-47-d12-1.360.I     09:38:11       09:38:11   
690026  15202.y102n.60-47-d12-1.360.I     09:39:39       09:39:39   
690027  15202.y102n.60-47-d12-1.360.I     09:40:21       09:40:21   
690028  15202.y102n.60-47-d12-1.360.I     09:41:06       09:41:06   
690029  15202.y102n.60-47-d12-1.360.I     09:41:45       09:41:45   
690030  15202.y102n.60-47-d12-1.360.I     09:42:43       09:42:43   
690031  15202.y102n.60-47-d12-1.360.I     09:43:45       09:43:45   
690032  15202.y102n.60-47-d12-1.360.I     09:44:52       09:44:52   
690033  15202.y102n.60-47-d12-1.360.I     09:45:14       09:45:14   
690034  15202.y102n.60-47-d12-1.360.I     09:45:47       09:45:47   
690035  15202.y102n.60-47-d12-1.360.I     09:46:42       09:46:42   
690036  15202.y102n.60-47-d12-1.360.I     09:47:26       09:47:26   
690037  15202.y102n.60-47-d12-1.360.I     09:48:02       09:48:02   
690038  15202.y102n.60-47-d12-1.360.I     09:48:31       09:48:31   
690039  15202.y102n.60-47-d12-1.360.I     09:48:59       09:48:59   
690040  15202.y102n.60-47-d12-1.360.I     09:49:28       09:49:28   
690041  15202.y102n.60-47-d12-1.360.I     09:50:04       09:50:04   
690042  15202.y102n.60-47-d12-1.360.I     09:51:07       09:51:07   
690043  15202.y102n.60-47-d12-1.360.I     09:51:48       09:51:48   
690044  15202.y102n.60-47-d12-1.360.I     09:53:04       09:53:04   
690045  15202.y102n.60-47-d12-1.360.I     09:54:56       09:54:56   
690046  15202.y102n.60-47-d12-1.360.I     09:56:04       09:56:04   
690047  15202.y102n.60-47-d12-1.360.I     09:57:51       09:57:51   
690048  15202.y102n.60-47-d12-1.360.I     09:59:40       09:59:40   
690049  15202.y102n.60-47-d12-1.360.I     10:00:24       10:00:24   
690050  15202.y102n.60-47-d12-1.360.I     10:00:41       10:00:41   
690051  15202.y102n.60-47-d12-1.360.I     10:01:20       10:01:20   
690052  15202.y102n.60-47-d12-1.360.I     10:02:05       10:02:05   
690053  15202.y102n.60-47-d12-1.360.I     10:02:25       10:02:25   
690054  15202.y102n.60-47-d12-1.360.I     10:03:12       10:03:12   
690055  15202.y102n.60-47-d12-1.360.I     10:03:56       10:03:56   
690056  15202.y102n.60-47-d12-1.360.I     10:04:14       10:04:14   
690057  15202.y102n.60-47-d12-1.360.I     10:05:03       10:05:03   
690058  15202.y102n.60-47-d12-1.360.I     10:05:45       10:05:45   
690059  15202.y102n.60-47-d12-1.360.I     10:06:23       10:06:23   
690060  15202.y102n.60-47-d12-1.360.I     10:07:31       10:07:31   
690061  15202.y102n.60-47-d12-1.360.I     10:09:05       10:09:05   
690062  15202.y102n.60-47-d12-1.360.I     10:09:56       10:09:56   
690063  15202.y102n.60-47-d12-1.360.I     10:10:24       10:10:24   
690064  15202.y102n.60-47-d12-1.360.I     10:11:14       10:11:14   
690065  15202.y102n.60-47-d12-1.360.I     10:11:55       10:11:55   
690066  15202.y102n.60-47-d12-1.360.I     10:13:09       10:13:09   
690067  15202.y102n.60-47-d12-1.360.I     10:18:54       10:18:54   
690068  15202.y102n.60-47-d12-1.360.I     10:18:59       10:18:59   

                   stop_id  stop_sequence    stop_headsign  pickup_type  \
690017        8250DB005013              1   Poolbeg Street            0   
690018        8250DB005014              2   Poolbeg Street            0   
690019        8250DB007291              3   Poolbeg Street            0   
690020        8250DB003485              4   Poolbeg Street            0 

After check the real time API, the NO.47 bus will not pass ths stop any more, So delete these data.

In [131]:
distance = distance[distance.stop_id != 'gen:57102:3542:0:1']

In [132]:
distance[distance["stop_id"] == 'gen:57102:3542:0:1']

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled, trip1, trip2, trip3, trip4, shape_id, new_stop_id]
Index: []

In [133]:
distance.loc[distance["stop_id"]=="gen:57102:3543:0:1","new_stop_id"] = 337

In [134]:
distance[distance['new_stop_id'] == '1']

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled, trip1, trip2, trip3, trip4, shape_id, new_stop_id]
Index: []

After these, all hava been changed

In [135]:
distance.trip3.unique()

array(['d12'], dtype=object)

In [136]:
group = distance.groupby(["trip2","stop_sequence"])
group.head(20)

trip_id arrival_time departure_time       stop_id  \
0         3643.y102m.60-1-d12-1.1.O     15:40:00       15:40:00  8240DB000226   
1         3643.y102m.60-1-d12-1.1.O     15:40:47       15:40:47  8240DB000228   
2         3643.y102m.60-1-d12-1.1.O     15:41:26       15:41:26  8240DB000229   
3         3643.y102m.60-1-d12-1.1.O     15:42:30       15:42:30  8240DB000227   
4         3643.y102m.60-1-d12-1.1.O     15:43:09       15:43:09  8240DB000230   
5         3643.y102m.60-1-d12-1.1.O     15:44:03       15:44:03  8240DB000231   
6         3643.y102m.60-1-d12-1.1.O     15:45:29       15:45:29  8220DB001641   
7         3643.y102m.60-1-d12-1.1.O     15:46:23       15:46:23  8220DB001642   
8         3643.y102m.60-1-d12-1.1.O     15:47:19       15:47:19  8220DB000213   
9         3643.y102m.60-1-d12-1.1.O     15:48:06       15:48:06  8220DB000214   
10        3643.y102m.60-1-d12-1.1.O     15:48:54       15:48:54  8220DB004432   
11        3643.y102m.60-1-d12-1.1.O     15:49:45       15:49:45  8220DB000119   
12        3643.y102m.60-1-d12-1.1.O     15:50:37       15:50:37  8220DB000044   
13        3643.y102m.60-1-d12-1.1.O     15:51:15       15:51:15   8220DB07603   
14        3643.y102m.60-1-d12-1.1.O     15:51:59       15:51:59  8220DB000045   
15        3643.y102m.60-1-d12-1.1.O     15:53:05       15:53:05  8220DB000046   
16        3643.y102m.60-1-d12-1.1.O     15:54:23       15:54:23  8220DB000047   
17        3643.y102m.60-1-d12-1.1.O     15:55:24       15:55:24  8220DB000048   
18        3643.y102m.60-1-d12-1.1.O     15:56:52       15:56:52  8220DB000049   
19        3643.y102m.60-1-d12-1.1.O     15:58:23       15:58:23  8220DB000051   
20        3643.y102m.60-1-d12-1.1.O     15:59:13       15:59:13  8220DB000052   
21        3643.y102m.60-1-d12-1.1.O     16:01:43       16:01:43  8220DB000265   
22        3643.y102m.60-1-d12-1.1.O     16:05:09       16:05:09  8220DB000271   
23        3643.y102m.60-1-d12-1.1.O     16:08:24       16:08:24  8220DB000340   
24        3643.y102m.60-1-d12-1.1.O     16:11:01       16:11:01  8220DB000350   
25        3643.y102m.60-1-d12-1.1.O     16:13:39       16:13:39  8220DB000351   
26        3643.y102m.60-1-d12-1.1.O     16:14:52       16:14:52  8220DB000352   
27        3643.y102m.60-1-d12-1.1.O     16:16:03       16:16:03  8220DB000353   
28        3643.y102m.60-1-d12-1.1.O     16:17:03       16:17:03  8220DB000354   
29        3643.y102m.60-1-d12-1.1.O     16:18:07       16:18:07  8220DB000355   
...                             ...          ...            ...           ...   
915272   5369.y102m.60-9-d12-1.13.I     17:38:56       17:38:56  8240DB006229   
915273   5369.y102m.60-9-d12-1.13.I     17:40:07       17:40:07  8240DB007131   
915339   5380.y102m.60-9-d12-1.13.I     17:48:56       17:48:56  8240DB006229   
915340   5380.y102m.60-9-d12-1.13.I     17:50:07       17:50:07  8240DB007131   
915406   5396.y102m.60-9-d12-1.13.I     16:18:56       16:18:56  8240DB006229   
915407   5396.y102m.60-9-d12-1.13.I     16:20:07       16:20:07  8240DB007131   
915473   5419.y102m.60-9-d12-1.13.I     17:58:56       17:58:56  8240DB006229   
915474   5419.y102m.60-9-d12-1.13.I     18:00:07       18:00:07  8240DB007131   
915540   5427.y102m.60-9-d12-1.13.I     17:03:56       17:03:56  8240DB006229   
915541   5427.y102m.60-9-d12-1.13.I     17:05:07       17:05:07  8240DB007131   
915607   5432.y102m.60-9-d12-1.13.I     18:08:56       18:08:56  8240DB006229   
915608   5432.y102m.60-9-d12-1.13.I     18:10:07       18:10:07  8240DB007131   
915674   5442.y102m.60-9-d12-1.13.I     17:18:56       17:18:56  8240DB006229   
915675   5442.y102m.60-9-d12-1.13.I     17:20:07       17:20:07  8240DB007131   
915741   5453.y102m.60-9-d12-1.13.I     17:28:56       17:28:56  8240DB006229   
915742   5453.y102m.60-9-d12-1.13.I     17:30:07       17:30:07  8240DB007131   
915808   5459.y102m.60-9-d12-1.13.I     16:33:56       16:33:56  8240DB006229   
915809   5459.y102m.60-9-d12-1.13.I     16:35:07       16:3

In [137]:
distance.dtypes

trip_id                 object
arrival_time            object
departure_time          object
stop_id                 object
stop_sequence            int64
stop_headsign           object
pickup_type              int64
drop_off_type            int64
shape_dist_traveled    float64
trip1                   object
trip2                   object
trip3                   object
trip4                   object
shape_id                object
new_stop_id             object
dtype: object

In [138]:
distance.loc[(distance["trip2"] == "1") & (distance["stop_sequence"] ==  1 ) ].departure_time.unique()

array(['15:40:00', '16:00:00', '15:00:00', '16:20:00', '15:20:00',
       '16:40:00', '17:00:00', '17:40:00', '17:20:00', '11:50:00',
       '13:50:00', '13:10:00', '12:30:00', '14:30:00', '13:30:00',
       '12:10:00', '14:10:00', '12:50:00', '09:00:00', '09:30:00',
       '18:30:00', '18:10:00', '17:50:00', '19:10:00', '20:30:00',
       '19:30:00', '18:50:00', '20:00:00', '18:20:00', '18:40:00',
       '18:00:00', '10:00:00', '11:00:00', '10:30:00', '11:30:00',
       '10:20:00', '10:40:00', '11:40:00', '11:20:00', '08:00:00',
       '08:30:00', '13:00:00', '13:20:00', '12:20:00', '13:40:00',
       '12:40:00', '14:20:00', '14:00:00', '12:00:00', '14:40:00',
       '17:10:00', '17:30:00', '16:50:00', '19:00:00', '22:30:00',
       '21:00:00', '23:00:00', '21:30:00', '22:00:00', '09:40:00',
       '09:20:00', '15:10:00', '16:30:00', '15:30:00', '16:10:00',
       '14:50:00', '15:50:00', '06:50:00', '06:30:00', '07:10:00',
       '07:20:00', '07:50:00', '07:40:00', '07:30:00', '08:20:

In [139]:
# since there is only one value in trip3, So this could be dropped
distance = distance.drop(["trip3"],axis=1)

In [140]:
distance.trip4.unique()

array(['1.1.O', '1.2.O', '1.3.O', '1.4.I', '1.5.I', '1.78.O', '1.79.I',
       '1.80.I', '1.81.O', '1.82.I', '1.15.O', '1.16.O', '1.17.I',
       '1.18.I', '1.83.O', '1.84.I', '1.85.I', '1.86.I', '1.87.O',
       '1.88.I', '1.89.O', '1.90.I', '1.91.I', '1.92.O', '1.93.O',
       '1.94.I', '1.95.I', '1.96.O', '1.97.O', '1.98.I', '1.99.I',
       '1.100.O', '1.101.O', '1.102.I', '1.103.I', '1.104.O', '1.105.O',
       '1.106.I', '1.107.I', '1.19.O', '1.20.O', '1.21.O', '1.22.O',
       '1.23.O', '1.24.O', '1.25.O', '1.26.O', '1.27.I', '1.28.I',
       '1.29.I', '1.30.I', '1.31.I', '1.32.I', '1.33.I', '1.34.I',
       '1.35.I', '1.36.I', '1.108.O', '1.109.I', '1.184.I', '1.185.O',
       '1.186.I', '1.110.O', '1.111.O', '1.112.I', '1.113.I', '1.114.O',
       '1.115.I', '1.116.I', '1.117.O', '1.466.I', '1.467.I', '1.468.I',
       '1.469.I', '1.470.I', '1.471.I', '1.472.O', '1.473.O', '1.474.O',
       '1.475.O', '1.476.O', '1.477.I', '1.478.I', '1.479.O', '1.480.I',
       '1.187.O', '1.

In [141]:
trip1_1=[]
trip1_2=[]
trip1_3=[]
trip4_2=[]
trip4_3=[]
trip_arrival =[]
for index, row in distance.iterrows():
    trip1_list = row["trip1"].split('.')
    trip1_1.append(trip1_list[0])
    trip1_2.append(trip1_list[1])
    trip1_3.append(trip1_list[2])
    trip4_list = row["trip4"].split('.')
    trip4_2.append(trip4_list[1])
    trip4_3.append(trip4_list[2])
    trip_arrival.append(int(row["arrival_time"].split(":")[0])*60*60 + int(row["arrival_time"].split(":")[1])*60 +int(row["arrival_time"].split(":")[2]))

In [142]:
distance['trip1_1']=trip1_1
distance['trip1_2']=trip1_2
distance['trip1_3']=trip1_3
distance['trip4_2']=trip4_2
distance['trip4_3']=trip4_3
distance["arrival_time"] = trip_arrival
distance["departure_time"]=trip_arrival

In [143]:
distance[(distance["stop_sequence"] == 2) & (distance["trip2"] == '145')]["new_stop_id"].unique()

array(['769', '774', '2997', '2061', '4203', '4844', '1476', '2007',
       '761', '4177', '406', '3144'], dtype=object)

In [148]:
def get_nextanddistance(group):
    group.sort_values(['stop_sequence'],ascending=True)
    group["distance"] = -(group.shape_dist_traveled.diff(periods=-1))
    group["time_period"] = -(group.arrival_time.diff(periods=-1))
    group["previous_stopID"] = group.new_stop_id.shift()
    group["hour"] = group.departure_time/60/60
    return group

In [149]:
distance.head()

trip_id  arrival_time  departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O         56400           56400  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O         56447           56447  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O         56486           56486  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O         56550           56550  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O         56589           56589  8240DB000230   

   stop_sequence stop_headsign  pickup_type  drop_off_type  \
0              1    Sandymount            0              0   
1              2    Sandymount            0              0   
2              3    Sandymount            0              0   
3              4    Sandymount            0              0   
4              5    Sandymount            0              0   

   shape_dist_traveled          trip1 trip2  trip4        shape_id  \
0             0.000000  3643.y102m.60     1  1.1.O  60-1-d12-1.1.O   
1           261.136188  3643.y102m.60     1  1.1.O  60-1-d12-1.1.O   
2           484.925289  3643.y102m.60     1  1.1.O  60-1-d12-1.1.O   
3           836.995679  3643.y102m.60     1  1.1.O  60-1-d12-1.1.O   
4          1066.461783  3643.y102m.60     1  1.1.O  60-1-d12-1.1.O   

  new_stop_id trip1_1 trip1_2 trip1_3 trip4_2 trip4_3  
0         226    3643   y102m      60       1       O  
1         228    3643   y102m      60       1       O  
2         229    3643   y102m      60       1       O  
3         227    3643   y102m      60       1       O  
4         230    3643   y102m      60       1       O

In [150]:
distance.trip2.unique()

array(['1', '102', '104', '11', '111', '114', '116', '118', '120', '122',
       '123', '13', '130', '14', '140', '142', '145', '14C', '15', '150',
       '151', '15A', '15B', '15D', '16', '161', '16C', '17', '17A', '18',
       '184', '185', '220', '236', '238', '239', '25', '25A', '25B',
       '25D', '25X', '26', '27', '270', '27A', '27B', '27X', '29A', '31',
       '31A', '31B', '31D', '32', '32X', '33', '33A', '33B', '33D', '33X',
       '37', '38', '38A', '38B', '38D', '39', '39A', '39X', '4', '40',
       '40B', '40D', '41', '41A', '41B', '41C', '41X', '42', '42D', '43',
       '44', '44B', '45A', '46A', '46E', '47', '49', '51D', '51X', '53',
       '54A', '56A', '59', '61', '63', '65', '65B', '66', '66A', '66B',
       '66X', '67', '67X', '68', '68A', '68X', '69', '69X', '7', '70',
       '70D', '747', '75', '757', '76', '76A', '77A', '77X', '79', '79A',
       '7A', '7B', '7D', '83', '83A', '84', '84A', '84X', '9'],
      dtype=object)

In [151]:
distance = distance.groupby(["trip_id"]).apply(get_nextanddistance)

In [152]:
distance["distance"].isnull().sum()

17342

In [153]:
distance.head()

trip_id  arrival_time  departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O         56400           56400  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O         56447           56447  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O         56486           56486  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O         56550           56550  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O         56589           56589  8240DB000230   

   stop_sequence stop_headsign  pickup_type  drop_off_type  \
0              1    Sandymount            0              0   
1              2    Sandymount            0              0   
2              3    Sandymount            0              0   
3              4    Sandymount            0              0   
4              5    Sandymount            0              0   

   shape_dist_traveled          trip1    ...     new_stop_id trip1_1 trip1_2  \
0             0.000000  3643.y102m.60    ...             226    3643   y102m   
1           261.136188  3643.y102m.60    ...             228    3643   y102m   
2           484.925289  3643.y102m.60    ...             229    3643   y102m   
3           836.995679  3643.y102m.60    ...             227    3643   y102m   
4          1066.461783  3643.y102m.60    ...             230    3643   y102m   

  trip1_3 trip4_2 trip4_3    distance time_period previous_stopID       hour  
0      60       1       O  261.136188        47.0             NaN  15.666667  
1      60       1       O  223.789101        39.0             226  15.679722  
2      60       1       O  352.070390        64.0             228  15.690556  
3      60       1       O  229.466104        39.0             229  15.708333  
4      60       1       O  292.654153        54.0             227  15.719167  

[5 rows x 23 columns]

In [154]:
distance.pickup_type.unique()

array([0, 1], dtype=int64)

In [155]:
distance.drop_off_type.unique()

array([0, 1], dtype=int64)

In [156]:
distance.trip1_3.unique()

array(['60'], dtype=object)

In [157]:
len(distance.trip1_1.unique())

17342

In [158]:
distance.trip4_3.unique()

array(['O', 'I'], dtype=object)

In [159]:
distance.trip4_2.unique()

array(['1', '2', '3', '4', '5', '78', '79', '80', '81', '82', '15', '16',
       '17', '18', '83', '84', '85', '86', '87', '88', '89', '90', '91',
       '92', '93', '94', '95', '96', '97', '98', '99', '100', '101',
       '102', '103', '104', '105', '106', '107', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33',
       '34', '35', '36', '108', '109', '184', '185', '186', '110', '111',
       '112', '113', '114', '115', '116', '117', '466', '467', '468',
       '469', '470', '471', '472', '473', '474', '475', '476', '477',
       '478', '479', '480', '187', '188', '196', '197', '198', '199',
       '118', '119', '120', '121', '122', '123', '124', '125', '200',
       '201', '202', '203', '204', '205', '206', '207', '208', '209',
       '210', '211', '189', '190', '191', '212', '213', '214', '215',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '126',
       '127', '128', '129', '130', '131', '132', '133', '47', '48', '4

In [160]:
# distance.loc[distance['stop_sequence']== 1,"distance"] = 0

In [161]:
distance.trip2.unique()

array(['1', '102', '104', '11', '111', '114', '116', '118', '120', '122',
       '123', '13', '130', '14', '140', '142', '145', '14C', '15', '150',
       '151', '15A', '15B', '15D', '16', '161', '16C', '17', '17A', '18',
       '184', '185', '220', '236', '238', '239', '25', '25A', '25B',
       '25D', '25X', '26', '27', '270', '27A', '27B', '27X', '29A', '31',
       '31A', '31B', '31D', '32', '32X', '33', '33A', '33B', '33D', '33X',
       '37', '38', '38A', '38B', '38D', '39', '39A', '39X', '4', '40',
       '40B', '40D', '41', '41A', '41B', '41C', '41X', '42', '42D', '43',
       '44', '44B', '45A', '46A', '46E', '47', '49', '51D', '51X', '53',
       '54A', '56A', '59', '61', '63', '65', '65B', '66', '66A', '66B',
       '66X', '67', '67X', '68', '68A', '68X', '69', '69X', '7', '70',
       '70D', '747', '75', '757', '76', '76A', '77A', '77X', '79', '79A',
       '7A', '7B', '7D', '83', '83A', '84', '84A', '84X', '9'],
      dtype=object)

In [162]:
# some renaming and columns dropping below
distance.rename(columns={'stop_sequence': 'prog_number', 'trip4_3': 'direction', 'trip2':'line_ID'}, inplace=True)
distance.head()

trip_id  arrival_time  departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O         56400           56400  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O         56447           56447  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O         56486           56486  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O         56550           56550  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O         56589           56589  8240DB000230   

   prog_number stop_headsign  pickup_type  drop_off_type  shape_dist_traveled  \
0            1    Sandymount            0              0             0.000000   
1            2    Sandymount            0              0           261.136188   
2            3    Sandymount            0              0           484.925289   
3            4    Sandymount            0              0           836.995679   
4            5    Sandymount            0              0          1066.461783   

           trip1    ...     new_stop_id trip1_1 trip1_2 trip1_3 trip4_2  \
0  3643.y102m.60    ...             226    3643   y102m      60       1   
1  3643.y102m.60    ...             228    3643   y102m      60       1   
2  3643.y102m.60    ...             229    3643   y102m      60       1   
3  3643.y102m.60    ...             227    3643   y102m      60       1   
4  3643.y102m.60    ...             230    3643   y102m      60       1   

  direction    distance time_period previous_stopID       hour  
0         O  261.136188        47.0             NaN  15.666667  
1         O  223.789101        39.0             226  15.679722  
2         O  352.070390        64.0             228  15.690556  
3         O  229.466104        39.0             229  15.708333  
4         O  292.654153        54.0             227  15.719167  

[5 rows x 23 columns]

In [163]:
distance = distance.drop(["trip1","trip4","trip4_2","trip1_1","trip1_3", "pickup_type","drop_off_type"],axis=1)

In [164]:
distance.rename(columns={'trip1_2': 'weekday'}, inplace=True)
distance.head()

trip_id  arrival_time  departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O         56400           56400  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O         56447           56447  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O         56486           56486  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O         56550           56550  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O         56589           56589  8240DB000230   

   prog_number stop_headsign  shape_dist_traveled line_ID        shape_id  \
0            1    Sandymount             0.000000       1  60-1-d12-1.1.O   
1            2    Sandymount           261.136188       1  60-1-d12-1.1.O   
2            3    Sandymount           484.925289       1  60-1-d12-1.1.O   
3            4    Sandymount           836.995679       1  60-1-d12-1.1.O   
4            5    Sandymount          1066.461783       1  60-1-d12-1.1.O   

  new_stop_id weekday direction    distance  time_period previous_stopID  \
0         226   y102m         O  261.136188         47.0             NaN   
1         228   y102m         O  223.789101         39.0             226   
2         229   y102m         O  352.070390         64.0             228   
3         227   y102m         O  229.466104         39.0             229   
4         230   y102m         O  292.654153         54.0             227   

        hour  
0  15.666667  
1  15.679722  
2  15.690556  
3  15.708333  
4  15.719167

In [165]:
# check the tyoe of the new lines id
distance["line_ID"].dtype

dtype('O')

In [166]:
distance.line_ID.unique()

array(['1', '102', '104', '11', '111', '114', '116', '118', '120', '122',
       '123', '13', '130', '14', '140', '142', '145', '14C', '15', '150',
       '151', '15A', '15B', '15D', '16', '161', '16C', '17', '17A', '18',
       '184', '185', '220', '236', '238', '239', '25', '25A', '25B',
       '25D', '25X', '26', '27', '270', '27A', '27B', '27X', '29A', '31',
       '31A', '31B', '31D', '32', '32X', '33', '33A', '33B', '33D', '33X',
       '37', '38', '38A', '38B', '38D', '39', '39A', '39X', '4', '40',
       '40B', '40D', '41', '41A', '41B', '41C', '41X', '42', '42D', '43',
       '44', '44B', '45A', '46A', '46E', '47', '49', '51D', '51X', '53',
       '54A', '56A', '59', '61', '63', '65', '65B', '66', '66A', '66B',
       '66X', '67', '67X', '68', '68A', '68X', '69', '69X', '7', '70',
       '70D', '747', '75', '757', '76', '76A', '77A', '77X', '79', '79A',
       '7A', '7B', '7D', '83', '83A', '84', '84A', '84X', '9'],
      dtype=object)

In [167]:
#distance['line_ID'] = distance['line_ID'].str.lower()
distance['stop_headsign'] = distance['stop_headsign'].str.strip()
distance.head()

trip_id  arrival_time  departure_time       stop_id  \
0  3643.y102m.60-1-d12-1.1.O         56400           56400  8240DB000226   
1  3643.y102m.60-1-d12-1.1.O         56447           56447  8240DB000228   
2  3643.y102m.60-1-d12-1.1.O         56486           56486  8240DB000229   
3  3643.y102m.60-1-d12-1.1.O         56550           56550  8240DB000227   
4  3643.y102m.60-1-d12-1.1.O         56589           56589  8240DB000230   

   prog_number stop_headsign  shape_dist_traveled line_ID        shape_id  \
0            1    Sandymount             0.000000       1  60-1-d12-1.1.O   
1            2    Sandymount           261.136188       1  60-1-d12-1.1.O   
2            3    Sandymount           484.925289       1  60-1-d12-1.1.O   
3            4    Sandymount           836.995679       1  60-1-d12-1.1.O   
4            5    Sandymount          1066.461783       1  60-1-d12-1.1.O   

  new_stop_id weekday direction    distance  time_period previous_stopID  \
0         226   y102m         O  261.136188         47.0             NaN   
1         228   y102m         O  223.789101         39.0             226   
2         229   y102m         O  352.070390         64.0             228   
3         227   y102m         O  229.466104         39.0             229   
4         230   y102m         O  292.654153         54.0             227   

        hour  
0  15.666667  
1  15.679722  
2  15.690556  
3  15.708333  
4  15.719167

In [168]:
distance.groupby('line_ID')['line_ID'].apply(lambda x: x.count())

line_ID
1      10014
102     8225
104     1750
11     12841
111     3154
114     1910
116      112
118       84
120     6535
122    14693
123    16299
13     28203
130    14804
14     18192
140    14234
142      684
145    30344
14C      274
15     27583
150     9000
151    12860
15A    10031
15B    12642
15D      128
16     27541
161      256
16C      459
17      9270
17A    15263
18     12501
       ...  
66B     3456
66X      759
67     13050
67X      981
68      6590
68A      109
68X       42
69      5537
69X       35
7      10568
70      4312
70D       77
747     7847
75     15328
757     3362
76      6760
76A      246
77A    18809
77X       65
79      6583
79A     3966
7A     11840
7B       502
7D       237
83     15969
83A     5359
84      7440
84A      652
84X      776
9      22718
Name: line_ID, Length: 128, dtype: int64

In [169]:
distance

trip_id  arrival_time  departure_time  \
0         3643.y102m.60-1-d12-1.1.O         56400           56400   
1         3643.y102m.60-1-d12-1.1.O         56447           56447   
2         3643.y102m.60-1-d12-1.1.O         56486           56486   
3         3643.y102m.60-1-d12-1.1.O         56550           56550   
4         3643.y102m.60-1-d12-1.1.O         56589           56589   
5         3643.y102m.60-1-d12-1.1.O         56643           56643   
6         3643.y102m.60-1-d12-1.1.O         56729           56729   
7         3643.y102m.60-1-d12-1.1.O         56783           56783   
8         3643.y102m.60-1-d12-1.1.O         56839           56839   
9         3643.y102m.60-1-d12-1.1.O         56886           56886   
10        3643.y102m.60-1-d12-1.1.O         56934           56934   
11        3643.y102m.60-1-d12-1.1.O         56985           56985   
12        3643.y102m.60-1-d12-1.1.O         57037           57037   
13        3643.y102m.60-1-d12-1.1.O         57075           57075   
14        3643.y102m.60-1-d12-1.1.O         57119           57119   
15        3643.y102m.60-1-d12-1.1.O         57185           57185   
16        3643.y102m.60-1-d12-1.1.O         57263           57263   
17        3643.y102m.60-1-d12-1.1.O         57324           57324   
18        3643.y102m.60-1-d12-1.1.O         57412           57412   
19        3643.y102m.60-1-d12-1.1.O         57503           57503   
20        3643.y102m.60-1-d12-1.1.O         57553           57553   
21        3643.y102m.60-1-d12-1.1.O         57703           57703   
22        3643.y102m.60-1-d12-1.1.O         57909           57909   
23        3643.y102m.60-1-d12-1.1.O         58104           58104   
24        3643.y102m.60-1-d12-1.1.O         58261           58261   
25        3643.y102m.60-1-d12-1.1.O         58419           58419   
26        3643.y102m.60-1-d12-1.1.O         58492           58492   
27        3643.y102m.60-1-d12-1.1.O         58563           58563   
28        3643.y102m.60-1-d12-1.1.O         58623           58623   
29        3643.y102m.60-1-d12-1.1.O         58687           58687   
...                             ...           ...             ...   
926175  16982.y102n.60-9-d12-1.14.I         84758           84758   
926176  16982.y102n.60-9-d12-1.14.I         84778           84778   
926177  16982.y102n.60-9-d12-1.14.I         84822           84822   
926178  16982.y102n.60-9-d12-1.14.I         84845           84845   
926179  16982.y102n.60-9-d12-1.14.I         84867           84867   
926180  16982.y102n.60-9-d12-1.14.I         84888           84888   
926181  16982.y102n.60-9-d12-1.14.I         84914           84914   
926182  16982.y102n.60-9-d12-1.14.I         84926           84926   
926183  16982.y102n.60-9-d12-1.14.I         84957           84957   
926184  16982.y102n.60-9-d12-1.14.I         84975           84975   
926185  16982.y102n.60-9-d12-1.14.I         84986           84986   
926186  16982.y102n.60-9-d12-1.14.I         85025           85025   
926187  16982.y102n.60-9-d12-1.14.I         85061           85061   
926188  16982.y102n.60-9-d12-1.14.I         85100           85100   
926189  16982.y102n.60-9-d12-1.14.I         85123           85123   
926190  16982.y102n.60-9-d12-1.14.I         85162           85162   
926191  16982.y102n.60-9-d12-1.14.I         85196           85196   
926192  16982.y102n.60-9-d12-1.14.I         85227           85227   
926193  16982.y102n.60-9-d12-1.14.I         85272           85272   
926194  16982.y102n.60-9-d12-1.14.I         85307           85307   
926195  16982.y102n.60-9-d12-1.14.I         85330           85330   
926196  16982.y102n.60-9-d12-1.14.I         85355           85355   
926197  16982.y102n.60-9-d12-1.14.I         85397           85397   
926198  16982.y102n.60-9-d12-1.14.I         85417           85417   
926199  16982.y102n.60-9-d12-1.14.I         85496           85496   
926200  16982.y102n.60-9-d12-1.14.I         85539           85539   
926201  16982.y102n.60-9-d

In [170]:
def get_destinationstop(group):
    group.sort_values(['prog_number'],ascending=False)
    max_sequence_row = group.ix[group['prog_number'].idxmax()]
    group["route_end_stop"] = max_sequence_row.new_stop_id
    return group
def get_departurestop(group):
    group.sort_values(['prog_number'],ascending=True)
    max_sequence_row = group.ix[group['prog_number'].idxmin()]
    group["route_start_stop"] = max_sequence_row.new_stop_id
    return group

In [171]:
def get_departuretime(group):
    group.sort_values(['prog_number'],ascending=True)
    min_sequence_row = group.ix[group['prog_number'].idxmin()]
    group["route_start_time"] = min_sequence_row.departure_time
    return group

def get_destinationtime(group):
    group.sort_values(['prog_number'],ascending=False)
    max_sequence_row = group.ix[group['prog_number'].idxmax()]
    group["route_end_time"] = max_sequence_row.departure_time
    return group


In [172]:
distance = distance.groupby(["trip_id"]).apply(get_destinationstop)
distance = distance.groupby(["trip_id"]).apply(get_departurestop)
distance = distance.groupby(["trip_id"]).apply(get_departuretime)
distance = distance.groupby(["trip_id"]).apply(get_destinationtime)

C:\Users\Di\Anaconda3\envs\bashi\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Di\Anaconda3\envs\bashi\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  
C:\Users\Di\Anaconda3\envs\bashi\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __na

In [173]:
distance["stop_sequence_count"] = distance.groupby(["trip_id"]).prog_number.transform(max)

In [174]:
distance_1 = distance.loc[distance['line_ID']== '1']

In [175]:
# distance.to_csv("distance_timetable.csv",index=False)

In [176]:
distance_1.groupby(["stop_headsign","weekday","direction"]).agg({'route_start_stop': pd.Series.unique,'route_end_stop': pd.Series.unique,'stop_sequence_count': pd.Series.unique})

route_start_stop route_end_stop  \
stop_headsign    weekday direction                                   
O'Connell Street y102m   I                      381           7615   
                         O                      226            271   
                 y102n   I                      381           7615   
                         O                      226            271   
                 y102o   I                      381           7615   
                         O                      226            271   
Sandymount       y102m   O               [226, 265]            380   
                 y102n   O                      226            380   
                 y102o   O                      226            380   
Shanard Road     y102m   I                      381            226   
                 y102n   I                      381            226   
                 y102o   I                      381            226   

                                   stop_sequence_count  
stop_headsign    weekday direction                      
O'Connell Street y102m   I                          22  
                         O                          23  
                 y102n   I                          22  
                         O                          23  
                 y102o   I                          22  
                         O                          23  
Sandymount       y102m   O                    [42, 21]  
                 y102n   O                          42  
                 y102o   O                          42  
Shanard Road     y102m   I                          43  
                 y102n   I                          43  
                 y102o   I                          43

In [177]:
distance.dtypes

trip_id                 object
arrival_time             int64
departure_time           int64
stop_id                 object
prog_number              int64
stop_headsign           object
shape_dist_traveled    float64
line_ID                 object
shape_id                object
new_stop_id             object
weekday                 object
direction               object
distance               float64
time_period            float64
previous_stopID         object
hour                   float64
route_end_stop          object
route_start_stop        object
route_start_time         int64
route_end_time           int64
stop_sequence_count      int64
dtype: object

In [178]:
distance["line_ID"] =  distance["line_ID"].astype("object")

In [179]:
distance["if_index"]= np.where(distance["arrival_time"] == distance["departure_time"], True , False)

In [180]:
distance

trip_id  arrival_time  departure_time  \
0         3643.y102m.60-1-d12-1.1.O         56400           56400   
1         3643.y102m.60-1-d12-1.1.O         56447           56447   
2         3643.y102m.60-1-d12-1.1.O         56486           56486   
3         3643.y102m.60-1-d12-1.1.O         56550           56550   
4         3643.y102m.60-1-d12-1.1.O         56589           56589   
5         3643.y102m.60-1-d12-1.1.O         56643           56643   
6         3643.y102m.60-1-d12-1.1.O         56729           56729   
7         3643.y102m.60-1-d12-1.1.O         56783           56783   
8         3643.y102m.60-1-d12-1.1.O         56839           56839   
9         3643.y102m.60-1-d12-1.1.O         56886           56886   
10        3643.y102m.60-1-d12-1.1.O         56934           56934   
11        3643.y102m.60-1-d12-1.1.O         56985           56985   
12        3643.y102m.60-1-d12-1.1.O         57037           57037   
13        3643.y102m.60-1-d12-1.1.O         57075           57075   
14        3643.y102m.60-1-d12-1.1.O         57119           57119   
15        3643.y102m.60-1-d12-1.1.O         57185           57185   
16        3643.y102m.60-1-d12-1.1.O         57263           57263   
17        3643.y102m.60-1-d12-1.1.O         57324           57324   
18        3643.y102m.60-1-d12-1.1.O         57412           57412   
19        3643.y102m.60-1-d12-1.1.O         57503           57503   
20        3643.y102m.60-1-d12-1.1.O         57553           57553   
21        3643.y102m.60-1-d12-1.1.O         57703           57703   
22        3643.y102m.60-1-d12-1.1.O         57909           57909   
23        3643.y102m.60-1-d12-1.1.O         58104           58104   
24        3643.y102m.60-1-d12-1.1.O         58261           58261   
25        3643.y102m.60-1-d12-1.1.O         58419           58419   
26        3643.y102m.60-1-d12-1.1.O         58492           58492   
27        3643.y102m.60-1-d12-1.1.O         58563           58563   
28        3643.y102m.60-1-d12-1.1.O         58623           58623   
29        3643.y102m.60-1-d12-1.1.O         58687           58687   
...                             ...           ...             ...   
926175  16982.y102n.60-9-d12-1.14.I         84758           84758   
926176  16982.y102n.60-9-d12-1.14.I         84778           84778   
926177  16982.y102n.60-9-d12-1.14.I         84822           84822   
926178  16982.y102n.60-9-d12-1.14.I         84845           84845   
926179  16982.y102n.60-9-d12-1.14.I         84867           84867   
926180  16982.y102n.60-9-d12-1.14.I         84888           84888   
926181  16982.y102n.60-9-d12-1.14.I         84914           84914   
926182  16982.y102n.60-9-d12-1.14.I         84926           84926   
926183  16982.y102n.60-9-d12-1.14.I         84957           84957   
926184  16982.y102n.60-9-d12-1.14.I         84975           84975   
926185  16982.y102n.60-9-d12-1.14.I         84986           84986   
926186  16982.y102n.60-9-d12-1.14.I         85025           85025   
926187  16982.y102n.60-9-d12-1.14.I         85061           85061   
926188  16982.y102n.60-9-d12-1.14.I         85100           85100   
926189  16982.y102n.60-9-d12-1.14.I         85123           85123   
926190  16982.y102n.60-9-d12-1.14.I         85162           85162   
926191  16982.y102n.60-9-d12-1.14.I         85196           85196   
926192  16982.y102n.60-9-d12-1.14.I         85227           85227   
926193  16982.y102n.60-9-d12-1.14.I         85272           85272   
926194  16982.y102n.60-9-d12-1.14.I         85307           85307   
926195  16982.y102n.60-9-d12-1.14.I         85330           85330   
926196  16982.y102n.60-9-d12-1.14.I         85355           85355   
926197  16982.y102n.60-9-d12-1.14.I         85397           85397   
926198  16982.y102n.60-9-d12-1.14.I         85417           85417   
926199  16982.y102n.60-9-d12-1.14.I         85496           85496   
926200  16982.y102n.60-9-d12-1.14.I         85539           85539   
926201  16982.y102n.60-9-d

In [181]:
distance = distance.drop(["arrival_time","if_index"],axis = 1)

In [182]:
distance.dtypes

trip_id                 object
departure_time           int64
stop_id                 object
prog_number              int64
stop_headsign           object
shape_dist_traveled    float64
line_ID                 object
shape_id                object
new_stop_id             object
weekday                 object
direction               object
distance               float64
time_period            float64
previous_stopID         object
hour                   float64
route_end_stop          object
route_start_stop        object
route_start_time         int64
route_end_time           int64
stop_sequence_count      int64
dtype: object

In [190]:
distance["hour"]=distance["hour"].astype("int")

In [192]:
distance["hour"].unique()

array([15, 16, 17, 18, 11, 12, 13, 14,  9, 10, 19, 20, 21,  8, 22, 23,  6,
        7, 24,  5,  4, 25], dtype=int64)

In [191]:
distance.head(10)

trip_id  departure_time       stop_id  prog_number  \
0  3643.y102m.60-1-d12-1.1.O           56400  8240DB000226            1   
1  3643.y102m.60-1-d12-1.1.O           56447  8240DB000228            2   
2  3643.y102m.60-1-d12-1.1.O           56486  8240DB000229            3   
3  3643.y102m.60-1-d12-1.1.O           56550  8240DB000227            4   
4  3643.y102m.60-1-d12-1.1.O           56589  8240DB000230            5   
5  3643.y102m.60-1-d12-1.1.O           56643  8240DB000231            6   
6  3643.y102m.60-1-d12-1.1.O           56729  8220DB001641            7   
7  3643.y102m.60-1-d12-1.1.O           56783  8220DB001642            8   
8  3643.y102m.60-1-d12-1.1.O           56839  8220DB000213            9   
9  3643.y102m.60-1-d12-1.1.O           56886  8220DB000214           10   

  stop_headsign  shape_dist_traveled line_ID        shape_id new_stop_id  \
0    Sandymount             0.000000       1  60-1-d12-1.1.O         226   
1    Sandymount           261.136188       1  60-1-d12-1.1.O         228   
2    Sandymount           484.925289       1  60-1-d12-1.1.O         229   
3    Sandymount           836.995679       1  60-1-d12-1.1.O         227   
4    Sandymount          1066.461783       1  60-1-d12-1.1.O         230   
5    Sandymount          1359.115936       1  60-1-d12-1.1.O         231   
6    Sandymount          1828.006229       1  60-1-d12-1.1.O        1641   
7    Sandymount          2121.780157       1  60-1-d12-1.1.O        1642   
8    Sandymount          2409.009386       1  60-1-d12-1.1.O         213   
9    Sandymount          2672.292228       1  60-1-d12-1.1.O         214   

  weekday direction    distance  time_period previous_stopID  hour  \
0   y102m         O  261.136188         47.0             NaN    15   
1   y102m         O  223.789101         39.0             226    15   
2   y102m         O  352.070390         64.0             228    15   
3   y102m         O  229.466104         39.0             229    15   
4   y102m         O  292.654153         54.0             227    15   
5   y102m         O  468.890293         86.0             230    15   
6   y102m         O  293.773927         54.0             231    15   
7   y102m         O  287.229230         56.0            1641    15   
8   y102m         O  263.282842         47.0            1642    15   
9   y102m         O  276.040589         48.0             213    15   

  route_end_stop route_start_stop  route_start_time  route_end_time  \
0            380              226             56400           59501   
1            380              226             56400           59501   
2            380              226             56400           59501   
3            380              226             56400           59501   
4            380              226             56400           59501   
5            380              226             56400           59501   
6            380              226             56400           59501   
7            380              226             56400           59501   
8            380              226             56400           59501   
9            380              226             56400           59501   

   stop_sequence_count  
0                   42  
1                   42  
2                   42  
3                   42  
4                   42  
5                   42  
6                   42  
7                   42  
8                   42  
9                   42

In [194]:
selected_distance=distance[["trip_id","departure_time","stop_headsign","prog_number","shape_dist_traveled","hour","distance","new_stop_id","line_ID","shape_id","weekday","previous_stopID","route_end_stop","route_start_stop","route_start_time","route_end_time"]]

In [195]:
selected_distance = selected_distance.rename(columns = {"new_stop_id":"stop_id"})

In [196]:
selected_distance[pd.isnull(selected_distance["previous_stopID"])]

trip_id  departure_time stop_headsign  \
0         3643.y102m.60-1-d12-1.1.O           56400    Sandymount   
42        3660.y102m.60-1-d12-1.1.O           57600    Sandymount   
84        3675.y102m.60-1-d12-1.1.O           54000    Sandymount   
126       3688.y102m.60-1-d12-1.1.O           58800    Sandymount   
168       3698.y102m.60-1-d12-1.1.O           55200    Sandymount   
210       3714.y102m.60-1-d12-1.1.O           60000    Sandymount   
252       9114.y102o.60-1-d12-1.1.O           61200    Sandymount   
294       9140.y102o.60-1-d12-1.1.O           63600    Sandymount   
336       9146.y102o.60-1-d12-1.1.O           62400    Sandymount   
378      16331.y102n.60-1-d12-1.1.O           42600    Sandymount   
420      16333.y102n.60-1-d12-1.1.O           49800    Sandymount   
462      16337.y102n.60-1-d12-1.1.O           47400    Sandymount   
504      16346.y102n.60-1-d12-1.1.O           45000    Sandymount   
546      16348.y102n.60-1-d12-1.1.O           52200    Sandymount   
588      16361.y102n.60-1-d12-1.1.O           48600    Sandymount   
630      16372.y102n.60-1-d12-1.1.O           43800    Sandymount   
672      16374.y102n.60-1-d12-1.1.O           51000    Sandymount   
714      16381.y102n.60-1-d12-1.1.O           46200    Sandymount   
756       9106.y102o.60-1-d12-1.1.O           32400    Sandymount   
798       9132.y102o.60-1-d12-1.1.O           34200    Sandymount   
840      16352.y102n.60-1-d12-1.1.O           66600    Sandymount   
882      16378.y102n.60-1-d12-1.1.O           65400    Sandymount   
924      16395.y102n.60-1-d12-1.1.O           64200    Sandymount   
966      16343.y102n.60-1-d12-1.1.O           69000    Sandymount   
1008     16354.y102n.60-1-d12-1.1.O           73800    Sandymount   
1050     16367.y102n.60-1-d12-1.1.O           70200    Sandymount   
1092     16387.y102n.60-1-d12-1.1.O           67800    Sandymount   
1134     16397.y102n.60-1-d12-1.1.O           72000    Sandymount   
1176      3645.y102m.60-1-d12-1.1.O           66000    Sandymount   
1218      3662.y102m.60-1-d12-1.1.O           67200    Sandymount   
...                             ...             ...           ...   
924319   5403.y102m.60-9-d12-1.13.I           30600   Charlestown   
924386   5445.y102m.60-9-d12-1.13.I           29100   Charlestown   
924453   5452.y102m.60-9-d12-1.13.I           29700   Charlestown   
924520   5455.y102m.60-9-d12-1.13.I           31500   Charlestown   
924587  16947.y102n.60-9-d12-1.13.I           56700   Charlestown   
924654  16955.y102n.60-9-d12-1.13.I           59400   Charlestown   
924721  16987.y102n.60-9-d12-1.13.I           58500   Charlestown   
924788  16992.y102n.60-9-d12-1.13.I           54000   Charlestown   
924855  16998.y102n.60-9-d12-1.13.I           60300   Charlestown   
924922  17002.y102n.60-9-d12-1.13.I           55800   Charlestown   
924989  17015.y102n.60-9-d12-1.13.I           57600   Charlestown   
925056  12712.y102o.60-9-d12-1.13.I           24600   Charlestown   
925123  12720.y102o.60-9-d12-1.13.I           72000   Charlestown   
925190  12729.y102o.60-9-d12-1.13.I           72900   Charlestown   
925257  12748.y102o.60-9-d12-1.13.I           74700   Charlestown   
925324  12767.y102o.60-9-d12-1.13.I           69600   Charlestown   
925391  12782.y102o.60-9-d12-1.13.I           68400   Charlestown   
925458  12794.y102o.60-9-d12-1.13.I           70800   Charlestown   
925525  12702.y102o.60-9-d12-1.13.I           76500   Charlestown   
925592  12731.y102o.60-9-d12-1.13.I           81900   Charlestown   
925659  12784.y102o.60-9-d12-1.13.I           78300   Charlestown   
925726  12796.y102o.60-9-d12-1.13.I           80100   Charlestown   
925793  16959.y102n.60-9-d12-1.13.I           81000   Charlestown   
925860  16972.y102n.60-9-d12-1.13.I           82800   Charlestown   
925927  17006.y102n.60-9-d12-1.13.I           77400   Charlestown   
925994  17019.y102n.60-9-d12-1.13.I           79200   Charlestown   
926061   5436.y102m.60-9-d

In [197]:
selected_distance

trip_id  departure_time stop_headsign  \
0         3643.y102m.60-1-d12-1.1.O           56400    Sandymount   
1         3643.y102m.60-1-d12-1.1.O           56447    Sandymount   
2         3643.y102m.60-1-d12-1.1.O           56486    Sandymount   
3         3643.y102m.60-1-d12-1.1.O           56550    Sandymount   
4         3643.y102m.60-1-d12-1.1.O           56589    Sandymount   
5         3643.y102m.60-1-d12-1.1.O           56643    Sandymount   
6         3643.y102m.60-1-d12-1.1.O           56729    Sandymount   
7         3643.y102m.60-1-d12-1.1.O           56783    Sandymount   
8         3643.y102m.60-1-d12-1.1.O           56839    Sandymount   
9         3643.y102m.60-1-d12-1.1.O           56886    Sandymount   
10        3643.y102m.60-1-d12-1.1.O           56934    Sandymount   
11        3643.y102m.60-1-d12-1.1.O           56985    Sandymount   
12        3643.y102m.60-1-d12-1.1.O           57037    Sandymount   
13        3643.y102m.60-1-d12-1.1.O           57075    Sandymount   
14        3643.y102m.60-1-d12-1.1.O           57119    Sandymount   
15        3643.y102m.60-1-d12-1.1.O           57185    Sandymount   
16        3643.y102m.60-1-d12-1.1.O           57263    Sandymount   
17        3643.y102m.60-1-d12-1.1.O           57324    Sandymount   
18        3643.y102m.60-1-d12-1.1.O           57412    Sandymount   
19        3643.y102m.60-1-d12-1.1.O           57503    Sandymount   
20        3643.y102m.60-1-d12-1.1.O           57553    Sandymount   
21        3643.y102m.60-1-d12-1.1.O           57703    Sandymount   
22        3643.y102m.60-1-d12-1.1.O           57909    Sandymount   
23        3643.y102m.60-1-d12-1.1.O           58104    Sandymount   
24        3643.y102m.60-1-d12-1.1.O           58261    Sandymount   
25        3643.y102m.60-1-d12-1.1.O           58419    Sandymount   
26        3643.y102m.60-1-d12-1.1.O           58492    Sandymount   
27        3643.y102m.60-1-d12-1.1.O           58563    Sandymount   
28        3643.y102m.60-1-d12-1.1.O           58623    Sandymount   
29        3643.y102m.60-1-d12-1.1.O           58687    Sandymount   
...                             ...             ...           ...   
926175  16982.y102n.60-9-d12-1.14.I           84758    Parnell Sq   
926176  16982.y102n.60-9-d12-1.14.I           84778    Parnell Sq   
926177  16982.y102n.60-9-d12-1.14.I           84822    Parnell Sq   
926178  16982.y102n.60-9-d12-1.14.I           84845    Parnell Sq   
926179  16982.y102n.60-9-d12-1.14.I           84867    Parnell Sq   
926180  16982.y102n.60-9-d12-1.14.I           84888    Parnell Sq   
926181  16982.y102n.60-9-d12-1.14.I           84914    Parnell Sq   
926182  16982.y102n.60-9-d12-1.14.I           84926    Parnell Sq   
926183  16982.y102n.60-9-d12-1.14.I           84957    Parnell Sq   
926184  16982.y102n.60-9-d12-1.14.I           84975    Parnell Sq   
926185  16982.y102n.60-9-d12-1.14.I           84986    Parnell Sq   
926186  16982.y102n.60-9-d12-1.14.I           85025    Parnell Sq   
926187  16982.y102n.60-9-d12-1.14.I           85061    Parnell Sq   
926188  16982.y102n.60-9-d12-1.14.I           85100    Parnell Sq   
926189  16982.y102n.60-9-d12-1.14.I           85123    Parnell Sq   
926190  16982.y102n.60-9-d12-1.14.I           85162    Parnell Sq   
926191  16982.y102n.60-9-d12-1.14.I           85196    Parnell Sq   
926192  16982.y102n.60-9-d12-1.14.I           85227    Parnell Sq   
926193  16982.y102n.60-9-d12-1.14.I           85272    Parnell Sq   
926194  16982.y102n.60-9-d12-1.14.I           85307    Parnell Sq   
926195  16982.y102n.60-9-d12-1.14.I           85330    Parnell Sq   
926196  16982.y102n.60-9-d12-1.14.I           85355    Parnell Sq   
926197  16982.y102n.60-9-d12-1.14.I           85397    Parnell Sq   
926198  16982.y102n.60-9-d12-1.14.I           85417    Parnell Sq   
926199  16982.y102n.60-9-d12-1.14.I           85496    Parnell Sq   
926200  16982.y102n.60-9-d12-1.14.I           85539    Parnell Sq   
926201  16982.y102n.60-9-d

In [199]:
distance.to_csv("full_timetable.csv",index=False)

In [198]:
selected_distance.to_csv("timetable.csv",index=False)

In [189]:
distance.groupby("trip_id").route_start_time.unique()

trip_id
1.y102m.60-33A-d12-1.154.I        [58500]
10.y102m.60-41C-d12-1.323.I       [30900]
100.y102m.60-41C-d12-1.322.I      [34800]
1000.y102m.60-13-d12-1.31.I       [84600]
10000.y102o.60-25-d12-1.216.I     [54300]
10001.y102o.60-25-d12-1.217.O     [57900]
10002.y102o.60-25-d12-1.216.I     [61500]
10003.y102o.60-25-d12-1.217.O     [65100]
10004.y102o.60-25-d12-1.216.I     [68700]
10005.y102o.60-25-d12-1.217.O     [72300]
10006.y102o.60-25-d12-1.216.I     [75600]
10007.y102o.60-25-d12-1.217.O     [79500]
10008.y102o.60-25-d12-1.216.I     [82800]
10009.y102o.60-25B-d12-1.221.O    [69420]
1001.y102m.60-76-d12-1.422.O      [23400]
10010.y102o.60-25B-d12-1.220.I    [73560]
10011.y102o.60-25B-d12-1.221.O    [78420]
10012.y102o.60-25B-d12-1.220.I    [82260]
10013.y102o.60-25A-d12-1.218.I    [21900]
10014.y102o.60-25A-d12-1.219.O    [25320]
10015.y102o.60-25A-d12-1.218.I    [29100]
10016.y102o.60-25A-d12-1.219.O    [32520]
10017.y102o.60-25A-d12-1.218.I    [36300]
10018.y102o.60-25A-d12-1.2